using Microsoft.CodeAnalysis;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace RandomSkunk.StructuredLogging.Generator;

[Generator]
[ExcludeFromCodeCoverage]
public class LogOperationExtensionsGenerator : IIncrementalGenerator
{
    private const string _summaryFormat = """
    /// <summary>
    /// Writes a structured log at the {0} level indicating that the specified operation is starting.
    /// </summary>
""";

    private const string _loggerParam = """
    /// <param name="logger">The <see cref="ILogger"/> to write to.</param>
""";

    private const string _eventIdParam = """
    /// <param name="eventId">The <see cref="EventId"/> associated with the operation.</param>
""";

    private const string _parameterMarkerParam = """
    /// <param name="parameterMarker">A unique, non-string parameter to divide operation properties and operation parameter
    /// names.</param>
""";

    private const string _logLevelParam = """
    /// <param name="logLevel">The level at which to log the operation.</param>
""";

    private const string _operationNameParam = """
    /// <param name="operationName">The name of the operation.</param>
""";

    private const string _propertyParam = """
    /// <param name="property">The operation property. If this value implements
    /// <c>IReadOnlyList&lt;KeyValuePair&lt;string, object?&gt;&gt;</c>, then it is used as operation log's properties.</param>
""";

    private const string _propertyNParamFormat = """
    /// <param name="property{0}">The {1} operation property.</param>
""";

    private const string _propertyNameParam = """
    /// <param name="propertyName">The name of the operation property, typically supplied automatically by the
    /// compiler. Ignored if <paramref name="property"/> implements
    /// <c>IReadOnlyList&lt;KeyValuePair&lt;string, object?&gt;&gt;</c>.</param>
""";

    private const string _propertyNNameParamFormat = """
    /// <param name="property{0}Name">The name of the {1} operation property, typically supplied automatically by the
    /// compiler.</param>
""";

    private const string _returnsFormat = """
    /// <returns>An <see cref="Operation{{TNameValuePairList}}"/> object that, when disposed, writes a structured log at the
    /// {0} level indicating that the operation is complete. To include the return value of the operation in this
    /// log, call the object's <see cref="Operation{{TNameValuePairList}}.Return"/> method before disposing it.</returns>
""";

    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("LogOperationExtensions.g.cs", GenerateLogOperationExtensionsPartialClass()));

    private static string GenerateLogOperationExtensionsPartialClass()
    {
        StringBuilder sb = new();

        sb.AppendLine("""
// <auto-generated/>

#nullable enable

using Microsoft.Extensions.Logging;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace RandomSkunk.StructuredLogging;

/// <content>
/// Defines the LogOperation extension methods. Each method returns the result of a call to one of the non-public GetOperation methods.
/// </content>
partial class LogOperationExtensions
{
""");

        GenerateMethods(sb, 0);
        GenerateMethods(sb, 1);
        GenerateMethods(sb, 2);
        GenerateMethods(sb, 3);
        GenerateMethods(sb, 4);
        GenerateMethods(sb, 5);
        GenerateMethods(sb, 6);
        GenerateMethods(sb, 7);
        GenerateMethods(sb, 8);

        while (char.IsWhiteSpace(sb[sb.Length - 1]))
            sb.Length--;
        sb.AppendLine();
        return sb.AppendLine("}").ToString();
    }

    private static void GenerateMethods(StringBuilder sb, int genericParameterCount)
    {
        GenerateMethod(sb, genericParameterCount, false, false);
        GenerateMethod(sb, genericParameterCount, false, true);
        GenerateMethod(sb, genericParameterCount, true, false);
        GenerateMethod(sb, genericParameterCount, true, true);
    }

    private static void GenerateMethod(StringBuilder sb, int genericParameterCount, bool eventIdParameter, bool logLevelParameter)
    {
        string logLevelDisplay = logLevelParameter ? "specified" : "debug";

        sb.AppendFormat(_summaryFormat, logLevelDisplay).AppendLine();
        
        sb.AppendLine(_loggerParam);
        
        if (logLevelParameter)
            sb.AppendLine(_logLevelParam);

        if (eventIdParameter)
            sb.AppendLine(_eventIdParam);
        
        sb.AppendLine(_operationNameParam);

        if (genericParameterCount == 1)
        {
            sb.AppendLine(_propertyParam);
            sb.AppendLine(_parameterMarkerParam);
            sb.AppendLine(_propertyNameParam);
        }
        else
        {
            for (int i = 1; i <= genericParameterCount; i++)
            {
                sb.AppendFormat(_propertyNParamFormat, i, GetOridinal(i)).AppendLine();
            }

            sb.AppendLine(_parameterMarkerParam);
            
            for (int i = 1; i <= genericParameterCount; i++)
            {
                sb.AppendFormat(_propertyNNameParamFormat, i, GetOridinal(i)).AppendLine();
            }
        }
        
        sb.AppendFormat(_returnsFormat, logLevelDisplay).AppendLine();

        sb.AppendFormat("""
    public static {0} LogOperation{1}(
        this ILogger? logger,
""", GetLogOperationType(genericParameterCount), GetGenericParameterDeclaration(genericParameterCount)).AppendLine();

        if (logLevelParameter)
        {
            sb.AppendLine("""
        LogLevel logLevel,
""");
        }

        if (eventIdParameter)
        {
            sb.AppendLine("""
        EventId eventId,
""");
        }

        if (logLevelParameter)
        {
            sb.Append("""
        [InterpolatedStringHandlerArgument(nameof(logger), nameof(logLevel))]
        ref InterpolatedString.OperationName operationName
""");
        }
        else
        {
            sb.Append("""
        [InterpolatedStringHandlerArgument(nameof(logger))]
        ref InterpolatedString.DebugOperationName operationName
""");
        }

        if (genericParameterCount == 0)
        {
            sb.AppendLine(") =>");
        }
        else if (genericParameterCount == 1)
        {
            sb.AppendLine(",").AppendLine("""
        T property,
        ParameterMarker parameterMarker = default,
        [CallerArgumentExpression(nameof(property))] string propertyName = null!) =>
""");
        }
        else if (genericParameterCount > 1)
        {
            sb.AppendLine(",");

            for (int i = 1; i <= genericParameterCount; i++)
            {
                sb.AppendFormat("""
        T{0} property{0},
""", i).AppendLine();
            }

            sb.AppendLine("""
        ParameterMarker parameterMarker = default,
""");

            for (int i = 1; i < genericParameterCount; i++)
            {
                sb.AppendFormat("""
        [CallerArgumentExpression(nameof(property{0}))] string property{0}Name = null!,
""", i).AppendLine();
            }

            sb.AppendFormat("""
        [CallerArgumentExpression(nameof(property{0}))] string property{0}Name = null!) =>
""", genericParameterCount).AppendLine();
        }

        sb.AppendLine("""
        logger.LogOperation(
""");

        if (logLevelParameter)
        {
            sb.AppendLine("""
            logLevel,
""");
        }
        else
        {
            sb.AppendLine("""
            LogLevel.Debug,
""");
        }

        if (eventIdParameter)
        {
            sb.AppendLine("""
            eventId,
""");
        }
        else
        {
            sb.AppendLine("""
            default,
""");
        }

        if (logLevelParameter)
        {
            sb.Append("""
            operationName.ToStringAndClear()
""");
        }
        else
        {
            sb.Append("""
            operationName._innerHandler.ToStringAndClear()
""");
        }

        if (genericParameterCount == 0)
        {
            sb.AppendLine(");");
        }
        else if (genericParameterCount == 1)
        {
            sb.AppendLine(",").AppendLine("""
            (propertyName, property));
""");
        }
        else if (genericParameterCount > 1)
        {
            sb.AppendLine(",");

            for (int i = 1; i < genericParameterCount; i++)
            {
                sb.AppendFormat("""
            (property{0}Name, property{0}),
""", i).AppendLine();
            }

            sb.AppendFormat("""
            (property{0}Name, property{0}));
""", genericParameterCount).AppendLine();
        }

        sb.AppendLine();
    }

    private static string? GetLogOperationType(int genericParameterCount) =>
        genericParameterCount switch
        {
            0 => "OperationLog<EmptyNameValuePairArray>",
            1 => "OperationLog<LogPropertyTuple<T>>",
            2 => "OperationLog<LogPropertyTuple<T1, T2>>",
            3 => "OperationLog<LogPropertyTuple<T1, T2, T3>>",
            4 => "OperationLog<LogPropertyTuple<T1, T2, T3, T4>>",
            5 => "OperationLog<LogPropertyTuple<T1, T2, T3, T4, T5>>",
            6 => "OperationLog<LogPropertyTuple<T1, T2, T3, T4, T5, T6>>",
            7 => "OperationLog<LogPropertyTuple<T1, T2, T3, T4, T5, T6, T7>>",
            8 => "OperationLog<LogPropertyTuple<T1, T2, T3, T4, T5, T6, T7, T8>>",
            _ => null,
        };

    private static string? GetGenericParameterDeclaration(int genericParameterCount) =>
        genericParameterCount switch
        {
            1 => "<T>",
            2 => "<T1, T2>",
            3 => "<T1, T2, T3>",
            4 => "<T1, T2, T3, T4>",
            5 => "<T1, T2, T3, T4, T5>",
            6 => "<T1, T2, T3, T4, T5, T6>",
            7 => "<T1, T2, T3, T4, T5, T6, T7>",
            8 => "<T1, T2, T3, T4, T5, T6, T7, T8>",
            _ => null,
        };

    private static string? GetOridinal(int i) =>
        i switch
        {
            1 => "first",
            2 => "second",
            3 => "third",
            4 => "fourth",
            5 => "fifth",
            6 => "sixth",
            7 => "seventh",
            8 => "eighth",
            _ => null
        };
}
