using Microsoft.CodeAnalysis;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace RandomSkunk.StructuredLogging.Generator;

/// <summary>
/// Provides an incremental source generator that generates structured logging extension methods for the <see
/// cref="ILogger"/> interface.
/// </summary>
/// <remarks>This generator creates a set of strongly-typed extension methods for structured logging, enabling
/// developers to log messages with interpolated strings, exceptions, event IDs, and  additional attributes. The
/// generated methods support various log levels (e.g., Trace, Debug, Information, Warning, Error, Critical) and
/// provide overloads for different combinations of  parameters.</remarks>
[Generator]
[ExcludeFromCodeCoverage]
public class StructuredLoggingExtensionsGenerator : IIncrementalGenerator
{
    private const string _summaryFormatNonInterpolatedMessage = """
    /// <summary>
    /// Writes a log entry at the {0} log level.
    /// </summary>
""";

    private const string _summaryFormatInterpolatedMessage = """
    /// <summary>
    /// Writes a log entry at the {0} log level with its message specified as an interpolated string.
    /// <para/>
    /// To capture a log attribute in an interpolation expression, specify a format that starts with an HTML tag. In <c>$"User
    /// {{user.Id:&lt;user-id&gt;}} logged in."</c>, the <c>user.Id</c> expression is captured in a log attribute named "user-id".
    /// In <c>$"Operation completed in {{elapsed.TotalSeconds:&lt;ElapsedSeconds&gt;0.000}} seconds."</c>, the log attribute is
    /// named "ElapsedSeconds" and "0.000" is used as the format string when rendering the value in the message.
    /// </summary>
""";

    private const string _loggerParam = """
    /// <param name="logger">The <see cref="ILogger"/> to write to.</param>
""";

    private const string _logLevelParam = """
    /// <param name="logLevel">The severity of the log.</param>
""";

    private const string _eventIdParam = """
    /// <param name="eventId">The event id associated with the log.</param>
""";

    private const string _exceptionParam = """
    /// <param name="exception">The exception to log.</param>
""";

    private const string _stringMessageParam = """
    /// <param name="message">The log message.</param>
""";

    private const string _interpolatedStringMessageParam = """
    /// <param name="interpolatedMessage">The log message as an interpolated string.</param>
""";

    private const string _logAttributesParam = """
    /// <param name="logAttributes">Key value pairs associated with the log.</param>
""";

    private const string _logAttributeParamFormat = """
    /// <param name="logAttribute{0}">The {1}key value pair associated with the log.</param>
""";

    private const string _keyValuePairsParam = """
    /// <param name="keyValuePairs">Key value pairs (e.g. <c>Dictionary&lt;string, object?&gt;</c>) associated with the log.
    /// </param>
""";

    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("StructuredLoggingExtensions.g.cs", GenerateStructuredLoggingExtensionsPartialClass()));

    private static string GenerateStructuredLoggingExtensionsPartialClass()
    {
        StringBuilder sb = new();

        sb.AppendLine("""
// <auto-generated/>

#nullable enable

using Microsoft.Extensions.Logging;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace RandomSkunk.StructuredLogging;

/// <content>
/// Defines the public API for the library. Each method calls one of the non-public WriteStructuredLog methods.
/// </content>
partial class StructuredLoggingExtensions
{
""");

        string?[] logLevels = [null, "Trace", "Debug", "Information", "Warning", "Error", "Critical"];
        GenerateMethods(sb, logLevels, logAttributesParameterType: LogAttributesParameterType.ParamsLogAttributeArray);
        GenerateMethods(sb, logLevels, logAttributesParameterType: LogAttributesParameterType.OneGenericParameter);
        GenerateMethods(sb, logLevels, logAttributesParameterType: LogAttributesParameterType.TwoGenericParameters);
        GenerateMethods(sb, logLevels, logAttributesParameterType: LogAttributesParameterType.ThreeGenericParameters);
        GenerateMethods(sb, logLevels, logAttributesParameterType: LogAttributesParameterType.FourGenericParameters);
        GenerateMethods(sb, logLevels, logAttributesParameterType: LogAttributesParameterType.FiveGenericParameters);
        GenerateMethods(sb, logLevels, logAttributesParameterType: LogAttributesParameterType.SixGenericParameters);
        GenerateMethods(sb, logLevels, logAttributesParameterType: LogAttributesParameterType.SevenGenericParameters);
        GenerateMethods(sb, logLevels, logAttributesParameterType: LogAttributesParameterType.EightGenericParameters);
        GenerateMethods(sb, logLevels, logAttributesParameterType: LogAttributesParameterType.KeyValuePairCollection);
        while (char.IsWhiteSpace(sb[sb.Length - 1]))
            sb.Length--;
        sb.AppendLine();
        return sb.AppendLine("}").ToString();
    }

    /// <param name="logAttributesParameterType"><c>true</c> to leave the type of the logAttributes parameter as a log attribute span or
    /// array. <c>false</c> to change the type to <c>IReadOnlyCollection&lt;KeyValuePair&lt;string, object?&gt;&gt;</c>.</param>
    private static void GenerateMethods(StringBuilder sb, string?[] logLevels, LogAttributesParameterType logAttributesParameterType)
    {
        foreach (string? logLevel in logLevels)
        {
            GenerateMethod(sb, logLevel, passThroughEventId: true, passThroughException: true, keepMessageType: true, logAttributesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: true, passThroughException: true, keepMessageType: false, logAttributesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: true, passThroughException: false, keepMessageType: true, logAttributesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: true, passThroughException: false, keepMessageType: false, logAttributesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: false, passThroughException: true, keepMessageType: true, logAttributesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: false, passThroughException: true, keepMessageType: false, logAttributesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: false, passThroughException: false, keepMessageType: true, logAttributesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: false, passThroughException: false, keepMessageType: false, logAttributesParameterType);
        }
    }

    /// <param name="passThroughEventId"><c>true</c> to generate the <c>eventId</c> parameter and pass it to the <c>Write</c> method. <c>false</c> to omit
    /// the eventId parameter and pass 0 to the <c>Write</c> method.</param>
    /// <param name="passThroughException"><c>true</c> to generate the exception parameter and pass it to the <c>Write</c> method. <c>false</c> to
    /// omit the exception parameter and pass null to the <c>Write</c> method.</param>
    /// <param name="keepMessageType"><c>true</c> to leave the type of the message parameter as a string. <c>false</c> to change the type to an
    /// interpolated string.</param>
    /// <param name="logAttributesParameterType">The type of the log attributes parameter</param>
    /// <param name="keepLogAttributesType"><c>true</c> to leave the type of the logAttributes parameter as a log attribute span or
    /// array. <c>false</c> to change the type to <c>IReadOnlyCollection&lt;KeyValuePair&lt;string, object?&gt;&gt;</c>.</param>
    private static void GenerateMethod(StringBuilder sb, string? logLevel, bool passThroughEventId, bool passThroughException, bool keepMessageType, LogAttributesParameterType logAttributesParameterType)
    {
        string logLevelDisplay = logLevel?.ToLower() ?? "specified";

        if (keepMessageType)
            sb.AppendFormat(_summaryFormatNonInterpolatedMessage, logLevelDisplay).AppendLine();
        else
            sb.AppendFormat(_summaryFormatInterpolatedMessage, logLevelDisplay).AppendLine();

        sb.AppendLine(_loggerParam);
        if (logLevel == null)
            sb.AppendLine(_logLevelParam);
        if (passThroughEventId)
            sb.AppendLine(_eventIdParam);
        if (passThroughException)
            sb.AppendLine(_exceptionParam);
        if (keepMessageType)
            sb.AppendLine(_stringMessageParam);
        else
            sb.AppendLine(_interpolatedStringMessageParam);

        AppendLogAttributeParams(sb, logAttributesParameterType);

        sb.AppendFormat("""
    public static void {0}{1}(
        this ILogger logger,
""", logLevel ?? "Write", GetGenericParameterDeclaration(logAttributesParameterType)).AppendLine();

        if (logLevel == null)
        {
            sb.AppendLine("""
        LogLevel logLevel,
""");
        }

        if (passThroughEventId)
        {
            sb.AppendLine("""
        EventId eventId,
""");
        }

        if (passThroughException)
        {
            sb.AppendLine("""
        Exception? exception,
""");
        }

        if (keepMessageType)
        {
            sb.AppendLine("""
        string? message,
""");
        }
        else
        {
            if (logLevel == null)
            {
                sb.AppendLine("""
        [InterpolatedStringHandlerArgument(nameof(logger), nameof(logLevel))]
        ref WriteInterpolatedStringHandler interpolatedMessage,
""");
            }
            else
            {
                sb.AppendFormat("""
        [InterpolatedStringHandlerArgument(nameof(logger))]
        ref {0}InterpolatedStringHandler interpolatedMessage,
""", logLevel).AppendLine();
            }
        }

        switch (logAttributesParameterType)
        {
            case LogAttributesParameterType.ParamsLogAttributeArray:
                sb.AppendLine("""
        params (string Key, object? Value)[] logAttributes) =>
""");
                break;
            case LogAttributesParameterType.KeyValuePairCollection:
                sb.AppendLine("""
        IReadOnlyCollection<KeyValuePair<string, object?>>? keyValuePairs) =>
""");
                break;
            case LogAttributesParameterType.OneGenericParameter:
                sb.AppendLine("""
        (string Key, T Value) logAttribute) =>
""");
                break;
            case LogAttributesParameterType.TwoGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logAttribute1,
        (string Key, T2 Value) logAttribute2) =>
""");
                break;
            case LogAttributesParameterType.ThreeGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logAttribute1,
        (string Key, T2 Value) logAttribute2,
        (string Key, T3 Value) logAttribute3) =>
""");
                break;
            case LogAttributesParameterType.FourGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logAttribute1,
        (string Key, T2 Value) logAttribute2,
        (string Key, T3 Value) logAttribute3,
        (string Key, T4 Value) logAttribute4) =>
""");
                break;
            case LogAttributesParameterType.FiveGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logAttribute1,
        (string Key, T2 Value) logAttribute2,
        (string Key, T3 Value) logAttribute3,
        (string Key, T4 Value) logAttribute4,
        (string Key, T5 Value) logAttribute5) =>
""");
                break;
            case LogAttributesParameterType.SixGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logAttribute1,
        (string Key, T2 Value) logAttribute2,
        (string Key, T3 Value) logAttribute3,
        (string Key, T4 Value) logAttribute4,
        (string Key, T5 Value) logAttribute5,
        (string Key, T6 Value) logAttribute6) =>
""");
                break;
            case LogAttributesParameterType.SevenGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logAttribute1,
        (string Key, T2 Value) logAttribute2,
        (string Key, T3 Value) logAttribute3,
        (string Key, T4 Value) logAttribute4,
        (string Key, T5 Value) logAttribute5,
        (string Key, T6 Value) logAttribute6,
        (string Key, T7 Value) logAttribute7) =>
""");
                break;
            case LogAttributesParameterType.EightGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logAttribute1,
        (string Key, T2 Value) logAttribute2,
        (string Key, T3 Value) logAttribute3,
        (string Key, T4 Value) logAttribute4,
        (string Key, T5 Value) logAttribute5,
        (string Key, T6 Value) logAttribute6,
        (string Key, T7 Value) logAttribute7,
        (string Key, T8 Value) logAttribute8) =>
""");
                break;
        }

        sb.Append("""
        logger.WriteStructuredLog(
""");

        if (logLevel == null)
        {
            sb.Append("logLevel, ");
        }
        else
        {
            sb.AppendFormat("LogLevel.{0}, ", logLevel);
        }

        if (passThroughEventId)
        {
            sb.Append("eventId, ");
        }
        else
        {
            sb.Append("0, ");
        }

        if (passThroughException)
        {
            sb.Append("exception, ");
        }
        else
        {
            sb.Append("null, ");
        }

        if (keepMessageType)
        {
            sb.Append("new(message), ");
        }
        else
        {
            sb.Append("interpolatedMessage.GetMessageDataAndClear(), ");
        }

        switch (logAttributesParameterType)
        {
            case LogAttributesParameterType.ParamsLogAttributeArray:
                sb.AppendLine("logAttributes);");
                break;
            case LogAttributesParameterType.KeyValuePairCollection:
                sb.AppendLine("keyValuePairs);");
                break;
            case LogAttributesParameterType.OneGenericParameter:
                sb.AppendLine("in logAttribute);");
                break;
            case LogAttributesParameterType.TwoGenericParameters:
                sb.AppendLine("in logAttribute1, in logAttribute2);");
                break;
            case LogAttributesParameterType.ThreeGenericParameters:
                sb.AppendLine("in logAttribute1, in logAttribute2, in logAttribute3);");
                break;
            case LogAttributesParameterType.FourGenericParameters:
                sb.AppendLine("in logAttribute1, in logAttribute2, in logAttribute3, in logAttribute4);");
                break;
            case LogAttributesParameterType.FiveGenericParameters:
                sb.AppendLine("in logAttribute1, in logAttribute2, in logAttribute3, in logAttribute4, in logAttribute5);");
                break;
            case LogAttributesParameterType.SixGenericParameters:
                sb.AppendLine("in logAttribute1, in logAttribute2, in logAttribute3, in logAttribute4, in logAttribute5, in logAttribute6);");
                break;
            case LogAttributesParameterType.SevenGenericParameters:
                sb.AppendLine("in logAttribute1, in logAttribute2, in logAttribute3, in logAttribute4, in logAttribute5, in logAttribute6, in logAttribute7);");
                break;
            case LogAttributesParameterType.EightGenericParameters:
                sb.AppendLine("in logAttribute1, in logAttribute2, in logAttribute3, in logAttribute4, in logAttribute5, in logAttribute6, in logAttribute7, in logAttribute8);");
                break;
        }

        sb.AppendLine();
    }

    private static void AppendLogAttributeParams(StringBuilder sb, LogAttributesParameterType logAttributesParameterType)
    {
        switch (logAttributesParameterType)
        {
            case LogAttributesParameterType.ParamsLogAttributeArray:
                sb.AppendLine(_logAttributesParam);
                return;
            case LogAttributesParameterType.KeyValuePairCollection:
                sb.AppendLine(_keyValuePairsParam);
                return;
        }

        for (int i = 1; i <= (int)logAttributesParameterType; i++)
        {
            sb.AppendFormat(_logAttributeParamFormat, i == 1 ? null : i, i switch
            {
                1 => null,
                2 => "second ",
                3 => "third ",
                4 => "fourth ",
                5 => "fifth ",
                6 => "sixth ",
                7 => "seventh ",
                8 => "eigth ",
                _ => throw new InvalidOperationException(),
            }).AppendLine();
        }
    }

    private static string? GetGenericParameterDeclaration(LogAttributesParameterType logAttributesParameterType) =>
        logAttributesParameterType switch
        {
            LogAttributesParameterType.OneGenericParameter => "<T>",
            LogAttributesParameterType.TwoGenericParameters => "<T1, T2>",
            LogAttributesParameterType.ThreeGenericParameters => "<T1, T2, T3>",
            LogAttributesParameterType.FourGenericParameters => "<T1, T2, T3, T4>",
            LogAttributesParameterType.FiveGenericParameters => "<T1, T2, T3, T4, T5>",
            LogAttributesParameterType.SixGenericParameters => "<T1, T2, T3, T4, T5, T6>",
            LogAttributesParameterType.SevenGenericParameters => "<T1, T2, T3, T4, T5, T6, T7>",
            LogAttributesParameterType.EightGenericParameters => "<T1, T2, T3, T4, T5, T6, T7, T8>",
            _ => null,
        };

    private enum LogAttributesParameterType
    {
        ParamsLogAttributeArray = -2,
        KeyValuePairCollection = -1,
        OneGenericParameter = 1,
        TwoGenericParameters = 2,
        ThreeGenericParameters = 3,
        FourGenericParameters = 4,
        FiveGenericParameters = 5,
        SixGenericParameters = 6,
        SevenGenericParameters = 7,
        EightGenericParameters = 8,
    }
}
