using Microsoft.CodeAnalysis;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace RandomSkunk.StructuredLogging.Generator;

/// <summary>
/// Provides an incremental source generator that generates structured logging extension methods for the
/// <c>Microsoft.Extensions.Logging.ILogger</c> interface.
/// </summary>
/// <remarks>This generator creates a set of strongly-typed extension methods for structured logging, enabling developers to log
/// messages with interpolated strings, exceptions, event IDs, and additional log properties. The generated methods support
/// various log levels (e.g., Trace, Debug, Information, Warning, Error, Critical) and provide overloads for different
/// combinations of parameters.</remarks>
[Generator]
[ExcludeFromCodeCoverage]
public class StructuredLoggingExtensionsGenerator : IIncrementalGenerator
{
    private const string _summaryFormatNonInterpolatedMessage = """
    /// <summary>
    /// Writes a log entry at the {0} log level.
    /// </summary>
""";

    private const string _summaryFormatInterpolatedMessage = """
    /// <summary>
    /// Writes a log entry at the {0} log level with its message specified as an interpolated string.
    /// <para/>
    /// To capture a log property in an interpolation expression, specify a format that starts with an HTML tag. In <c>$"User
    /// {{user.Id:&lt;user-id&gt;}} logged in."</c>, the <c>user.Id</c> expression is captured in a log property named "user-id".
    /// In <c>$"Operation completed in {{elapsed.TotalSeconds:&lt;ElapsedSeconds&gt;0.000}} seconds."</c>, the log property is
    /// named "ElapsedSeconds" and "0.000" is used as the format string when rendering the value in the message.
    /// </summary>
""";

    private const string _loggerParam = """
    /// <param name="logger">The <see cref="ILogger"/> to write to.</param>
""";

    private const string _logLevelParam = """
    /// <param name="logLevel">The severity of the log.</param>
""";

    private const string _eventIdParam = """
    /// <param name="eventId">The event id associated with the log.</param>
""";

    private const string _exceptionParam = """
    /// <param name="exception">The exception to log.</param>
""";

    private const string _stringMessageParam = """
    /// <param name="message">The log message.</param>
""";

    private const string _interpolatedStringMessageParam = """
    /// <param name="interpolatedMessage">The log message as an interpolated string.</param>
""";

    private const string _logPropertyArrayParam = """
    /// <param name="logProperties">Name value pairs associated with the log.</param>
""";

    private const string _logPropertyParamFormat = """
    /// <param name="logProperty{0}">The {1}name value pair associated with the log.</param>
""";

    private const string _nameValuePairCollectionParam = """
    /// <param name="logProperties">Name value pairs (e.g. <c>Dictionary&lt;string, object?&gt;</c>) associated with the log.
    /// </param>
""";

    private const string _nameValuePairListParam = """
    /// <param name="logProperties">Name value pairs associated with the log.
    /// </param>
""";

    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("StructuredLoggingExtensions.g.cs", GenerateStructuredLoggingExtensionsPartialClass()));

    private static string GenerateStructuredLoggingExtensionsPartialClass()
    {
        StringBuilder sb = new();

        sb.AppendLine("""
// <auto-generated/>

#nullable enable

using Microsoft.Extensions.Logging;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace RandomSkunk.StructuredLogging;

/// <content>
/// Defines the public API for the library. Each method calls one of the non-public WriteStructuredLog methods.
/// </content>
partial class StructuredLoggingExtensions
{
""");

        string?[] logLevels = [null, "Trace", "Debug", "Information", "Warning", "Error", "Critical"];
        GenerateMethods(sb, logLevels, logPropertiesParameterType: LogPropertiesParameterType.ParamsLogPropertyArray);
        GenerateMethods(sb, logLevels, logPropertiesParameterType: LogPropertiesParameterType.OneGenericParameter);
        GenerateMethods(sb, logLevels, logPropertiesParameterType: LogPropertiesParameterType.TwoGenericParameters);
        GenerateMethods(sb, logLevels, logPropertiesParameterType: LogPropertiesParameterType.ThreeGenericParameters);
        GenerateMethods(sb, logLevels, logPropertiesParameterType: LogPropertiesParameterType.FourGenericParameters);
        GenerateMethods(sb, logLevels, logPropertiesParameterType: LogPropertiesParameterType.FiveGenericParameters);
        GenerateMethods(sb, logLevels, logPropertiesParameterType: LogPropertiesParameterType.SixGenericParameters);
        GenerateMethods(sb, logLevels, logPropertiesParameterType: LogPropertiesParameterType.SevenGenericParameters);
        GenerateMethods(sb, logLevels, logPropertiesParameterType: LogPropertiesParameterType.EightGenericParameters);
        GenerateMethods(sb, logLevels, logPropertiesParameterType: LogPropertiesParameterType.NameValuePairCollection);
        GenerateMethods(sb, logLevels, logPropertiesParameterType: LogPropertiesParameterType.NameValuePairList);
        while (char.IsWhiteSpace(sb[sb.Length - 1]))
            sb.Length--;
        sb.AppendLine();
        return sb.AppendLine("}").ToString();
    }

    private static void GenerateMethods(StringBuilder sb, string?[] logLevels, LogPropertiesParameterType logPropertiesParameterType)
    {
        foreach (string? logLevel in logLevels)
        {
            GenerateMethod(sb, logLevel, passThroughEventId: true, passThroughException: true, keepMessageType: true, logPropertiesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: true, passThroughException: true, keepMessageType: false, logPropertiesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: true, passThroughException: false, keepMessageType: true, logPropertiesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: true, passThroughException: false, keepMessageType: false, logPropertiesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: false, passThroughException: true, keepMessageType: true, logPropertiesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: false, passThroughException: true, keepMessageType: false, logPropertiesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: false, passThroughException: false, keepMessageType: true, logPropertiesParameterType);
            GenerateMethod(sb, logLevel, passThroughEventId: false, passThroughException: false, keepMessageType: false, logPropertiesParameterType);
        }
    }

    /// <param name="passThroughEventId"><c>true</c> to generate the <c>eventId</c> parameter and pass it to the <c>Write</c> method. <c>false</c> to omit
    /// the eventId parameter and pass 0 to the <c>Write</c> method.</param>
    /// <param name="passThroughException"><c>true</c> to generate the exception parameter and pass it to the <c>Write</c> method. <c>false</c> to
    /// omit the exception parameter and pass null to the <c>Write</c> method.</param>
    /// <param name="keepMessageType"><c>true</c> to leave the type of the message parameter as a string. <c>false</c> to change the type to an
    /// interpolated string.</param>
    /// <param name="logPropertiesParameterType">The type of the log properties parameter</param>
    private static void GenerateMethod(StringBuilder sb, string? logLevel, bool passThroughEventId, bool passThroughException, bool keepMessageType, LogPropertiesParameterType logPropertiesParameterType)
    {
        string logLevelDisplay = logLevel?.ToLower() ?? "specified";

        if (keepMessageType)
            sb.AppendFormat(_summaryFormatNonInterpolatedMessage, logLevelDisplay).AppendLine();
        else
            sb.AppendFormat(_summaryFormatInterpolatedMessage, logLevelDisplay).AppendLine();

        sb.AppendLine(_loggerParam);
        if (logLevel == null)
            sb.AppendLine(_logLevelParam);
        if (passThroughEventId)
            sb.AppendLine(_eventIdParam);
        if (passThroughException)
            sb.AppendLine(_exceptionParam);
        if (keepMessageType)
            sb.AppendLine(_stringMessageParam);
        else
            sb.AppendLine(_interpolatedStringMessageParam);

        AppendLogPropertyParams(sb, logPropertiesParameterType);

        sb.AppendFormat("""
    public static void {0}{1}(
        this ILogger logger,
""", logLevel ?? "Write", GetGenericParameterDeclaration(logPropertiesParameterType)).AppendLine();

        if (logLevel == null)
        {
            sb.AppendLine("""
        LogLevel logLevel,
""");
        }

        if (passThroughEventId)
        {
            sb.AppendLine("""
        EventId eventId,
""");
        }

        if (passThroughException)
        {
            sb.AppendLine("""
        Exception? exception,
""");
        }

        if (keepMessageType)
        {
            sb.AppendLine("""
        string? message,
""");
        }
        else
        {
            if (logLevel == null)
            {
                sb.AppendLine("""
        [InterpolatedStringHandlerArgument(nameof(logger), nameof(logLevel))]
        ref WriteInterpolatedStringHandler interpolatedMessage,
""");
            }
            else
            {
                sb.AppendFormat("""
        [InterpolatedStringHandlerArgument(nameof(logger))]
        ref {0}InterpolatedStringHandler interpolatedMessage,
""", logLevel).AppendLine();
            }
        }

        switch (logPropertiesParameterType)
        {
            case LogPropertiesParameterType.ParamsLogPropertyArray:
                sb.AppendLine("""
        params (string Key, object? Value)[] logProperties) =>
""");
                break;
            case LogPropertiesParameterType.NameValuePairCollection:
                sb.AppendLine("""
        IReadOnlyCollection<KeyValuePair<string, object?>>? logProperties) =>
""");
                break;
            case LogPropertiesParameterType.NameValuePairList:
                sb.AppendLine("""
        IReadOnlyList<KeyValuePair<string, object?>>? logProperties) =>
""");
                break;
            case LogPropertiesParameterType.OneGenericParameter:
                sb.AppendLine("""
        (string Key, T Value) logProperty) =>
""");
                break;
            case LogPropertiesParameterType.TwoGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logProperty1,
        (string Key, T2 Value) logProperty2) =>
""");
                break;
            case LogPropertiesParameterType.ThreeGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logProperty1,
        (string Key, T2 Value) logProperty2,
        (string Key, T3 Value) logProperty3) =>
""");
                break;
            case LogPropertiesParameterType.FourGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logProperty1,
        (string Key, T2 Value) logProperty2,
        (string Key, T3 Value) logProperty3,
        (string Key, T4 Value) logProperty4) =>
""");
                break;
            case LogPropertiesParameterType.FiveGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logProperty1,
        (string Key, T2 Value) logProperty2,
        (string Key, T3 Value) logProperty3,
        (string Key, T4 Value) logProperty4,
        (string Key, T5 Value) logProperty5) =>
""");
                break;
            case LogPropertiesParameterType.SixGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logProperty1,
        (string Key, T2 Value) logProperty2,
        (string Key, T3 Value) logProperty3,
        (string Key, T4 Value) logProperty4,
        (string Key, T5 Value) logProperty5,
        (string Key, T6 Value) logProperty6) =>
""");
                break;
            case LogPropertiesParameterType.SevenGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logProperty1,
        (string Key, T2 Value) logProperty2,
        (string Key, T3 Value) logProperty3,
        (string Key, T4 Value) logProperty4,
        (string Key, T5 Value) logProperty5,
        (string Key, T6 Value) logProperty6,
        (string Key, T7 Value) logProperty7) =>
""");
                break;
            case LogPropertiesParameterType.EightGenericParameters:
                sb.AppendLine("""
        (string Key, T1 Value) logProperty1,
        (string Key, T2 Value) logProperty2,
        (string Key, T3 Value) logProperty3,
        (string Key, T4 Value) logProperty4,
        (string Key, T5 Value) logProperty5,
        (string Key, T6 Value) logProperty6,
        (string Key, T7 Value) logProperty7,
        (string Key, T8 Value) logProperty8) =>
""");
                break;
        }

        sb.Append("""
        logger.WriteStructuredLog(
""");

        if (logLevel == null)
        {
            sb.Append("logLevel, ");
        }
        else
        {
            sb.AppendFormat("LogLevel.{0}, ", logLevel);
        }

        if (passThroughEventId)
        {
            sb.Append("eventId, ");
        }
        else
        {
            sb.Append("0, ");
        }

        if (passThroughException)
        {
            sb.Append("exception, ");
        }
        else
        {
            sb.Append("null, ");
        }

        if (keepMessageType)
        {
            sb.Append("new(message), ");
        }
        else
        {
            sb.Append("interpolatedMessage.GetMessageDataAndClear(), ");
        }

        switch (logPropertiesParameterType)
        {
            case LogPropertiesParameterType.ParamsLogPropertyArray:
            case LogPropertiesParameterType.NameValuePairCollection:
            case LogPropertiesParameterType.NameValuePairList:
                sb.AppendLine("logProperties);");
                break;
            case LogPropertiesParameterType.OneGenericParameter:
                sb.AppendLine("in logProperty);");
                break;
            case LogPropertiesParameterType.TwoGenericParameters:
                sb.AppendLine("in logProperty1, in logProperty2);");
                break;
            case LogPropertiesParameterType.ThreeGenericParameters:
                sb.AppendLine("in logProperty1, in logProperty2, in logProperty3);");
                break;
            case LogPropertiesParameterType.FourGenericParameters:
                sb.AppendLine("in logProperty1, in logProperty2, in logProperty3, in logProperty4);");
                break;
            case LogPropertiesParameterType.FiveGenericParameters:
                sb.AppendLine("in logProperty1, in logProperty2, in logProperty3, in logProperty4, in logProperty5);");
                break;
            case LogPropertiesParameterType.SixGenericParameters:
                sb.AppendLine("in logProperty1, in logProperty2, in logProperty3, in logProperty4, in logProperty5, in logProperty6);");
                break;
            case LogPropertiesParameterType.SevenGenericParameters:
                sb.AppendLine("in logProperty1, in logProperty2, in logProperty3, in logProperty4, in logProperty5, in logProperty6, in logProperty7);");
                break;
            case LogPropertiesParameterType.EightGenericParameters:
                sb.AppendLine("in logProperty1, in logProperty2, in logProperty3, in logProperty4, in logProperty5, in logProperty6, in logProperty7, in logProperty8);");
                break;
        }

        sb.AppendLine();
    }

    private static void AppendLogPropertyParams(StringBuilder sb, LogPropertiesParameterType logPropertiesParameterType)
    {
        switch (logPropertiesParameterType)
        {
            case LogPropertiesParameterType.ParamsLogPropertyArray:
                sb.AppendLine(_logPropertyArrayParam);
                return;
            case LogPropertiesParameterType.NameValuePairCollection:
                sb.AppendLine(_nameValuePairCollectionParam);
                return;
            case LogPropertiesParameterType.NameValuePairList:
                sb.AppendLine(_nameValuePairListParam);
                return;
            case LogPropertiesParameterType.OneGenericParameter:
                sb.AppendFormat(_logPropertyParamFormat, null, null).AppendLine();
                return;
        }

        for (int i = 1; i <= (int)logPropertiesParameterType; i++)
        {
            sb.AppendFormat(_logPropertyParamFormat, i, i switch
            {
                1 => "first ",
                2 => "second ",
                3 => "third ",
                4 => "fourth ",
                5 => "fifth ",
                6 => "sixth ",
                7 => "seventh ",
                8 => "eigth ",
                _ => throw new InvalidOperationException(),
            }).AppendLine();
        }
    }

    private static string? GetGenericParameterDeclaration(LogPropertiesParameterType logPropertiesParameterType) =>
        logPropertiesParameterType switch
        {
            LogPropertiesParameterType.OneGenericParameter => "<T>",
            LogPropertiesParameterType.TwoGenericParameters => "<T1, T2>",
            LogPropertiesParameterType.ThreeGenericParameters => "<T1, T2, T3>",
            LogPropertiesParameterType.FourGenericParameters => "<T1, T2, T3, T4>",
            LogPropertiesParameterType.FiveGenericParameters => "<T1, T2, T3, T4, T5>",
            LogPropertiesParameterType.SixGenericParameters => "<T1, T2, T3, T4, T5, T6>",
            LogPropertiesParameterType.SevenGenericParameters => "<T1, T2, T3, T4, T5, T6, T7>",
            LogPropertiesParameterType.EightGenericParameters => "<T1, T2, T3, T4, T5, T6, T7, T8>",
            _ => null,
        };

    private enum LogPropertiesParameterType
    {
        ParamsLogPropertyArray = -3,
        NameValuePairCollection = -2,
        NameValuePairList = -1,
        OneGenericParameter = 1,
        TwoGenericParameters = 2,
        ThreeGenericParameters = 3,
        FourGenericParameters = 4,
        FiveGenericParameters = 5,
        SixGenericParameters = 6,
        SevenGenericParameters = 7,
        EightGenericParameters = 8,
    }
}
