using Microsoft.CodeAnalysis;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace RandomSkunk.StructuredLogging.Generator;

/// <summary>
/// Provides an incremental source generator that generates structured logging extension methods for the <see
/// cref="ILogger"/> interface.
/// </summary>
/// <remarks>This generator creates a set of strongly-typed extension methods for structured logging, enabling
/// developers to log messages with interpolated strings, exceptions, event IDs, and  additional attributes. The
/// generated methods support various log levels (e.g., Trace, Debug, Information, Warning, Error, Critical) and
/// provide overloads for different combinations of  parameters.</remarks>
[Generator]
[ExcludeFromCodeCoverage]
public class StructuredLoggingExtensionsGenerator : IIncrementalGenerator
{
    private const string _writeSummaryFormat = """
    /// <summary>
    /// Writes a log entry at the {0} log level.
    /// </summary>
""";

    private const string _loggerParam = """
    /// <param name="logger">The <see cref="ILogger"/> to write to.</param>
""";

    private const string _logLevelParam = """
    /// <param name="logLevel">Entry will be written on this level.</param>
""";

    private const string _eventIdParam = """
    /// <param name="eventId">The event id associated with the log.</param>
""";

    private const string _exceptionParam = """
    /// <param name="exception">The exception to log.</param>
""";

    private const string _stringMessageParam = """
    /// <param name="message">The log message.</param>
""";

    private const string _interpolatedStringMessageParamFormat = """
    /// <param name="message">The log message as an interpolated string. Evaluated only if the logger is enabled at the {0}
    /// log level.</param>
""";

    private const string _logAttributesParam = """
    /// <param name="logAttributes">Key value pairs associated with the log.</param>
""";

    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("StructuredLoggingExtensions.g.cs", GenerateStructuredLoggingExtensionsPartialClass()));

    private static string GenerateStructuredLoggingExtensionsPartialClass()
    {
        StringBuilder sb = new();

        sb.AppendLine("""
// <auto-generated/>
// ReSharper disable All

using Microsoft.Extensions.Logging;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace RandomSkunk.StructuredLogging;

using LogAttributeSpanOrArray =
#if NET9_0_OR_GREATER
    Span<(string Key, object? Value)>;
#else
    (string Key, object? Value)[];
#endif

/// <remarks>
/// Defines pass-through extension methods.
/// </remarks>
[ExcludeFromCodeCoverage]
public static partial class StructuredLoggingExtensions
{
""");

        string?[] logLevels = [null, "Trace", "Debug", "Information", "Warning", "Error", "Critical"];
        GenerateMethods(sb, logLevels, keepLogAttributesType: true);
        GenerateMethods(sb, logLevels, keepLogAttributesType: false);
        while (char.IsWhiteSpace(sb[sb.Length - 1]))
            sb.Length--;
        sb.AppendLine();
        return sb.AppendLine("}").ToString();
    }

    /// <param name="keepLogAttributesType"><c>true</c> to leave the type of the logAttributes parameter as a log attribute span or
    /// array. <c>false</c> to change the type to <c>IReadOnlyCollection&lt;KeyValuePair&lt;string, object?&gt;&gt;</c>.</param>
    private static void GenerateMethods(StringBuilder sb, string?[] logLevels, bool keepLogAttributesType)
    {
        foreach (string? logLevel in logLevels)
        {
            if (logLevel != null) // Skip the two Write overloads that are already defined in the main extension class.
                GenerateMethod(sb, logLevel, passThroughEventId: true, passThroughException: true, keepMessageType: true, keepLogAttributesType);

            GenerateMethod(sb, logLevel, passThroughEventId: true, passThroughException: true, keepMessageType: false, keepLogAttributesType);
            GenerateMethod(sb, logLevel, passThroughEventId: true, passThroughException: false, keepMessageType: true, keepLogAttributesType);
            GenerateMethod(sb, logLevel, passThroughEventId: true, passThroughException: false, keepMessageType: false, keepLogAttributesType);
            GenerateMethod(sb, logLevel, passThroughEventId: false, passThroughException: true, keepMessageType: true, keepLogAttributesType);
            GenerateMethod(sb, logLevel, passThroughEventId: false, passThroughException: true, keepMessageType: false, keepLogAttributesType);
            GenerateMethod(sb, logLevel, passThroughEventId: false, passThroughException: false, keepMessageType: true, keepLogAttributesType);
            GenerateMethod(sb, logLevel, passThroughEventId: false, passThroughException: false, keepMessageType: false, keepLogAttributesType);
        }
    }

    /// <param name="passThroughEventId"><c>true</c> to generate the <c>eventId</c> parameter and pass it to the <c>Write</c> method. <c>false</c> to omit
    /// the eventId parameter and pass 0 to the <c>Write</c> method.</param>
    /// <param name="passThroughException"><c>true</c> to generate the exception parameter and pass it to the <c>Write</c> method. <c>false</c> to
    /// omit the exception parameter and pass null to the <c>Write</c> method.</param>
    /// <param name="keepMessageType"><c>true</c> to leave the type of the message parameter as a string. <c>false</c> to change the type to an
    /// interpolated string.</param>
    /// <param name="keepLogAttributesType"><c>true</c> to leave the type of the logAttributes parameter as a log attribute span or
    /// array. <c>false</c> to change the type to <c>IReadOnlyCollection&lt;KeyValuePair&lt;string, object?&gt;&gt;</c>.</param>
    private static void GenerateMethod(StringBuilder sb, string? logLevel, bool passThroughEventId, bool passThroughException, bool keepMessageType, bool keepLogAttributesType)
    {
        string logLevelDisplay = logLevel?.ToLower() ?? "specified";

        sb.AppendFormat(_writeSummaryFormat, logLevelDisplay).AppendLine();
        sb.AppendLine(_loggerParam);
        if (logLevel == null)
            sb.AppendLine(_logLevelParam);
        if (passThroughEventId)
            sb.AppendLine(_eventIdParam);
        if (passThroughException)
            sb.AppendLine(_exceptionParam);
        if (keepMessageType)
            sb.AppendLine(_stringMessageParam);
        else
            sb.AppendFormat(_interpolatedStringMessageParamFormat, logLevelDisplay).AppendLine();
        sb.AppendLine(_logAttributesParam);
        sb.AppendFormat("""
    public static void {0}(
        this ILogger logger,
""", logLevel ?? "Write").AppendLine();

        if (logLevel == null)
        {
            sb.AppendLine("""
        LogLevel logLevel,
""");
        }

        if (passThroughEventId)
        {
            sb.AppendLine("""
        EventId eventId,
""");
        }

        if (passThroughException)
        {
            sb.AppendLine("""
        Exception? exception,
""");
        }

        if (keepMessageType)
        {
            sb.AppendLine("""
        string? message,
""");
        }
        else
        {
            if (logLevel == null)
            {
                sb.AppendLine("""
        [InterpolatedStringHandlerArgument(nameof(logger), nameof(logLevel))]
        ref InterpolatedString message,
""");
            }
            else
            {
                sb.AppendFormat("""
        [InterpolatedStringHandlerArgument(nameof(logger))]
        ref InterpolatedString<{0}> message,
""", logLevel).AppendLine();
            }
        }

        if (keepLogAttributesType)
        {
            sb.AppendLine("""
        params LogAttributeSpanOrArray logAttributes) =>
""");
        }
        else
        {
            sb.AppendLine("""
        IReadOnlyCollection<KeyValuePair<string, object?>> logAttributes) =>
""");
        }

        sb.Append("""
        logger.Write(
""");

        if (logLevel == null)
        {
            sb.Append("logLevel, ");
        }
        else
        {
            sb.AppendFormat("LogLevel.{0}, ", logLevel);
        }

        if (passThroughEventId)
        {
            sb.Append("eventId, ");
        }
        else
        {
            sb.Append("0, ");
        }

        if (passThroughException)
        {
            sb.Append("exception, ");
        }
        else
        {
            sb.Append("null, ");
        }

        if (keepMessageType)
        {
            sb.Append("message, ");
        }
        else
        {
            sb.Append("message.ToStringAndClear(), ");
        }

        sb.AppendLine("logAttributes);");
        sb.AppendLine();
    }
}
