// <auto-generated/>
#nullable enable
using System.Globalization;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.Logging;

namespace RandomSkunk.StructuredLogging;

/// <summary>
/// Interpolated string handler for the message parameter of the Trace-level <see cref="StructuredLoggerExtensions"/> methods. Building the message is skipped when the Trace level is not enabled for the target <see cref="ILogger"/>. A format starting with an <c>&lt;PropertyName&gt;</c> tag also captures that interpolated value as a structured property named <c>PropertyName</c>; any remaining format text after the tag is used to format the value in the message. An empty tag (<c>&lt;&gt;</c>) opts out of capturing while still allowing the remaining format to start with '&lt;'. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
/// </summary>
[InterpolatedStringHandler]
public ref struct TraceInterpolatedStringHandler
{
    private DefaultInterpolatedStringHandler _handler;
    private List<KeyValuePair<string, object?>>? _capturedProperties;
    internal readonly bool IsEnabled;

    /// <summary>
    /// Initializes the handler and checks whether the Trace level is enabled for <paramref name="logger"/>.
    /// </summary>
    /// <param name="literalLength">The total number of characters in the interpolated string's literal text.</param>
    /// <param name="formattedCount">The number of interpolation expressions in the interpolated string.</param>
    /// <param name="logger">The logger the message is being built for.</param>
    /// <param name="handlerIsValid">Set to <see langword="false"/> when the Trace level is not enabled for <paramref name="logger"/>, so the compiler skips evaluating and appending the interpolated string's arguments.</param>
    public TraceInterpolatedStringHandler(int literalLength, int formattedCount, ILogger logger, out bool handlerIsValid)
    {
        IsEnabled = handlerIsValid = logger.IsEnabled(LogLevel.Trace);
        _handler = handlerIsValid
            ? new DefaultInterpolatedStringHandler(literalLength, formattedCount, CultureInfo.InvariantCulture)
            : default;
        _capturedProperties = null;
    }

    /// <summary>
    /// Appends a literal text segment of the interpolated string to the message.
    /// </summary>
    /// <param name="value">The literal text to append.</param>
    public void AppendLiteral(string value) => _handler.AppendLiteral(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    public void AppendFormatted<T>(T value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            LogPropertyDestructuring.AppendDestructured(ref _handler, value);
        else
            _handler.AppendFormatted(value, tag.Format);
    }

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted<T>(T value, int alignment) => _handler.AppendFormatted(value, alignment);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, int alignment, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            _handler.AppendFormatted(LogPropertyDestructuring.Render(value), alignment);
        else
            _handler.AppendFormatted(value, alignment, tag.Format);
    }

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    public void AppendFormatted(string? value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted(string? value, int alignment) => _handler.AppendFormatted(value, alignment);

    internal string ToStringAndClear() => _handler.ToStringAndClear();

    internal IReadOnlyList<KeyValuePair<string, object?>> GetCapturedProperties() =>
        _capturedProperties ?? (IReadOnlyList<KeyValuePair<string, object?>>)[];
}

/// <summary>
/// Interpolated string handler for the message parameter of the Debug-level <see cref="StructuredLoggerExtensions"/> methods. Building the message is skipped when the Debug level is not enabled for the target <see cref="ILogger"/>. A format starting with an <c>&lt;PropertyName&gt;</c> tag also captures that interpolated value as a structured property named <c>PropertyName</c>; any remaining format text after the tag is used to format the value in the message. An empty tag (<c>&lt;&gt;</c>) opts out of capturing while still allowing the remaining format to start with '&lt;'. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
/// </summary>
[InterpolatedStringHandler]
public ref struct DebugInterpolatedStringHandler
{
    private DefaultInterpolatedStringHandler _handler;
    private List<KeyValuePair<string, object?>>? _capturedProperties;
    internal readonly bool IsEnabled;

    /// <summary>
    /// Initializes the handler and checks whether the Debug level is enabled for <paramref name="logger"/>.
    /// </summary>
    /// <param name="literalLength">The total number of characters in the interpolated string's literal text.</param>
    /// <param name="formattedCount">The number of interpolation expressions in the interpolated string.</param>
    /// <param name="logger">The logger the message is being built for.</param>
    /// <param name="handlerIsValid">Set to <see langword="false"/> when the Debug level is not enabled for <paramref name="logger"/>, so the compiler skips evaluating and appending the interpolated string's arguments.</param>
    public DebugInterpolatedStringHandler(int literalLength, int formattedCount, ILogger logger, out bool handlerIsValid)
    {
        IsEnabled = handlerIsValid = logger.IsEnabled(LogLevel.Debug);
        _handler = handlerIsValid
            ? new DefaultInterpolatedStringHandler(literalLength, formattedCount, CultureInfo.InvariantCulture)
            : default;
        _capturedProperties = null;
    }

    /// <summary>
    /// Appends a literal text segment of the interpolated string to the message.
    /// </summary>
    /// <param name="value">The literal text to append.</param>
    public void AppendLiteral(string value) => _handler.AppendLiteral(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    public void AppendFormatted<T>(T value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            LogPropertyDestructuring.AppendDestructured(ref _handler, value);
        else
            _handler.AppendFormatted(value, tag.Format);
    }

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted<T>(T value, int alignment) => _handler.AppendFormatted(value, alignment);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, int alignment, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            _handler.AppendFormatted(LogPropertyDestructuring.Render(value), alignment);
        else
            _handler.AppendFormatted(value, alignment, tag.Format);
    }

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    public void AppendFormatted(string? value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted(string? value, int alignment) => _handler.AppendFormatted(value, alignment);

    internal string ToStringAndClear() => _handler.ToStringAndClear();

    internal IReadOnlyList<KeyValuePair<string, object?>> GetCapturedProperties() =>
        _capturedProperties ?? (IReadOnlyList<KeyValuePair<string, object?>>)[];
}

/// <summary>
/// Interpolated string handler for the message parameter of the Information-level <see cref="StructuredLoggerExtensions"/> methods. Building the message is skipped when the Information level is not enabled for the target <see cref="ILogger"/>. A format starting with an <c>&lt;PropertyName&gt;</c> tag also captures that interpolated value as a structured property named <c>PropertyName</c>; any remaining format text after the tag is used to format the value in the message. An empty tag (<c>&lt;&gt;</c>) opts out of capturing while still allowing the remaining format to start with '&lt;'. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
/// </summary>
[InterpolatedStringHandler]
public ref struct InformationInterpolatedStringHandler
{
    private DefaultInterpolatedStringHandler _handler;
    private List<KeyValuePair<string, object?>>? _capturedProperties;
    internal readonly bool IsEnabled;

    /// <summary>
    /// Initializes the handler and checks whether the Information level is enabled for <paramref name="logger"/>.
    /// </summary>
    /// <param name="literalLength">The total number of characters in the interpolated string's literal text.</param>
    /// <param name="formattedCount">The number of interpolation expressions in the interpolated string.</param>
    /// <param name="logger">The logger the message is being built for.</param>
    /// <param name="handlerIsValid">Set to <see langword="false"/> when the Information level is not enabled for <paramref name="logger"/>, so the compiler skips evaluating and appending the interpolated string's arguments.</param>
    public InformationInterpolatedStringHandler(int literalLength, int formattedCount, ILogger logger, out bool handlerIsValid)
    {
        IsEnabled = handlerIsValid = logger.IsEnabled(LogLevel.Information);
        _handler = handlerIsValid
            ? new DefaultInterpolatedStringHandler(literalLength, formattedCount, CultureInfo.InvariantCulture)
            : default;
        _capturedProperties = null;
    }

    /// <summary>
    /// Appends a literal text segment of the interpolated string to the message.
    /// </summary>
    /// <param name="value">The literal text to append.</param>
    public void AppendLiteral(string value) => _handler.AppendLiteral(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    public void AppendFormatted<T>(T value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            LogPropertyDestructuring.AppendDestructured(ref _handler, value);
        else
            _handler.AppendFormatted(value, tag.Format);
    }

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted<T>(T value, int alignment) => _handler.AppendFormatted(value, alignment);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, int alignment, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            _handler.AppendFormatted(LogPropertyDestructuring.Render(value), alignment);
        else
            _handler.AppendFormatted(value, alignment, tag.Format);
    }

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    public void AppendFormatted(string? value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted(string? value, int alignment) => _handler.AppendFormatted(value, alignment);

    internal string ToStringAndClear() => _handler.ToStringAndClear();

    internal IReadOnlyList<KeyValuePair<string, object?>> GetCapturedProperties() =>
        _capturedProperties ?? (IReadOnlyList<KeyValuePair<string, object?>>)[];
}

/// <summary>
/// Interpolated string handler for the message parameter of the Warning-level <see cref="StructuredLoggerExtensions"/> methods. Building the message is skipped when the Warning level is not enabled for the target <see cref="ILogger"/>. A format starting with an <c>&lt;PropertyName&gt;</c> tag also captures that interpolated value as a structured property named <c>PropertyName</c>; any remaining format text after the tag is used to format the value in the message. An empty tag (<c>&lt;&gt;</c>) opts out of capturing while still allowing the remaining format to start with '&lt;'. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
/// </summary>
[InterpolatedStringHandler]
public ref struct WarningInterpolatedStringHandler
{
    private DefaultInterpolatedStringHandler _handler;
    private List<KeyValuePair<string, object?>>? _capturedProperties;
    internal readonly bool IsEnabled;

    /// <summary>
    /// Initializes the handler and checks whether the Warning level is enabled for <paramref name="logger"/>.
    /// </summary>
    /// <param name="literalLength">The total number of characters in the interpolated string's literal text.</param>
    /// <param name="formattedCount">The number of interpolation expressions in the interpolated string.</param>
    /// <param name="logger">The logger the message is being built for.</param>
    /// <param name="handlerIsValid">Set to <see langword="false"/> when the Warning level is not enabled for <paramref name="logger"/>, so the compiler skips evaluating and appending the interpolated string's arguments.</param>
    public WarningInterpolatedStringHandler(int literalLength, int formattedCount, ILogger logger, out bool handlerIsValid)
    {
        IsEnabled = handlerIsValid = logger.IsEnabled(LogLevel.Warning);
        _handler = handlerIsValid
            ? new DefaultInterpolatedStringHandler(literalLength, formattedCount, CultureInfo.InvariantCulture)
            : default;
        _capturedProperties = null;
    }

    /// <summary>
    /// Appends a literal text segment of the interpolated string to the message.
    /// </summary>
    /// <param name="value">The literal text to append.</param>
    public void AppendLiteral(string value) => _handler.AppendLiteral(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    public void AppendFormatted<T>(T value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            LogPropertyDestructuring.AppendDestructured(ref _handler, value);
        else
            _handler.AppendFormatted(value, tag.Format);
    }

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted<T>(T value, int alignment) => _handler.AppendFormatted(value, alignment);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, int alignment, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            _handler.AppendFormatted(LogPropertyDestructuring.Render(value), alignment);
        else
            _handler.AppendFormatted(value, alignment, tag.Format);
    }

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    public void AppendFormatted(string? value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted(string? value, int alignment) => _handler.AppendFormatted(value, alignment);

    internal string ToStringAndClear() => _handler.ToStringAndClear();

    internal IReadOnlyList<KeyValuePair<string, object?>> GetCapturedProperties() =>
        _capturedProperties ?? (IReadOnlyList<KeyValuePair<string, object?>>)[];
}

/// <summary>
/// Interpolated string handler for the message parameter of the Error-level <see cref="StructuredLoggerExtensions"/> methods. Building the message is skipped when the Error level is not enabled for the target <see cref="ILogger"/>. A format starting with an <c>&lt;PropertyName&gt;</c> tag also captures that interpolated value as a structured property named <c>PropertyName</c>; any remaining format text after the tag is used to format the value in the message. An empty tag (<c>&lt;&gt;</c>) opts out of capturing while still allowing the remaining format to start with '&lt;'. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
/// </summary>
[InterpolatedStringHandler]
public ref struct ErrorInterpolatedStringHandler
{
    private DefaultInterpolatedStringHandler _handler;
    private List<KeyValuePair<string, object?>>? _capturedProperties;
    internal readonly bool IsEnabled;

    /// <summary>
    /// Initializes the handler and checks whether the Error level is enabled for <paramref name="logger"/>.
    /// </summary>
    /// <param name="literalLength">The total number of characters in the interpolated string's literal text.</param>
    /// <param name="formattedCount">The number of interpolation expressions in the interpolated string.</param>
    /// <param name="logger">The logger the message is being built for.</param>
    /// <param name="handlerIsValid">Set to <see langword="false"/> when the Error level is not enabled for <paramref name="logger"/>, so the compiler skips evaluating and appending the interpolated string's arguments.</param>
    public ErrorInterpolatedStringHandler(int literalLength, int formattedCount, ILogger logger, out bool handlerIsValid)
    {
        IsEnabled = handlerIsValid = logger.IsEnabled(LogLevel.Error);
        _handler = handlerIsValid
            ? new DefaultInterpolatedStringHandler(literalLength, formattedCount, CultureInfo.InvariantCulture)
            : default;
        _capturedProperties = null;
    }

    /// <summary>
    /// Appends a literal text segment of the interpolated string to the message.
    /// </summary>
    /// <param name="value">The literal text to append.</param>
    public void AppendLiteral(string value) => _handler.AppendLiteral(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    public void AppendFormatted<T>(T value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            LogPropertyDestructuring.AppendDestructured(ref _handler, value);
        else
            _handler.AppendFormatted(value, tag.Format);
    }

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted<T>(T value, int alignment) => _handler.AppendFormatted(value, alignment);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, int alignment, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            _handler.AppendFormatted(LogPropertyDestructuring.Render(value), alignment);
        else
            _handler.AppendFormatted(value, alignment, tag.Format);
    }

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    public void AppendFormatted(string? value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted(string? value, int alignment) => _handler.AppendFormatted(value, alignment);

    internal string ToStringAndClear() => _handler.ToStringAndClear();

    internal IReadOnlyList<KeyValuePair<string, object?>> GetCapturedProperties() =>
        _capturedProperties ?? (IReadOnlyList<KeyValuePair<string, object?>>)[];
}

/// <summary>
/// Interpolated string handler for the message parameter of the Critical-level <see cref="StructuredLoggerExtensions"/> methods. Building the message is skipped when the Critical level is not enabled for the target <see cref="ILogger"/>. A format starting with an <c>&lt;PropertyName&gt;</c> tag also captures that interpolated value as a structured property named <c>PropertyName</c>; any remaining format text after the tag is used to format the value in the message. An empty tag (<c>&lt;&gt;</c>) opts out of capturing while still allowing the remaining format to start with '&lt;'. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
/// </summary>
[InterpolatedStringHandler]
public ref struct CriticalInterpolatedStringHandler
{
    private DefaultInterpolatedStringHandler _handler;
    private List<KeyValuePair<string, object?>>? _capturedProperties;
    internal readonly bool IsEnabled;

    /// <summary>
    /// Initializes the handler and checks whether the Critical level is enabled for <paramref name="logger"/>.
    /// </summary>
    /// <param name="literalLength">The total number of characters in the interpolated string's literal text.</param>
    /// <param name="formattedCount">The number of interpolation expressions in the interpolated string.</param>
    /// <param name="logger">The logger the message is being built for.</param>
    /// <param name="handlerIsValid">Set to <see langword="false"/> when the Critical level is not enabled for <paramref name="logger"/>, so the compiler skips evaluating and appending the interpolated string's arguments.</param>
    public CriticalInterpolatedStringHandler(int literalLength, int formattedCount, ILogger logger, out bool handlerIsValid)
    {
        IsEnabled = handlerIsValid = logger.IsEnabled(LogLevel.Critical);
        _handler = handlerIsValid
            ? new DefaultInterpolatedStringHandler(literalLength, formattedCount, CultureInfo.InvariantCulture)
            : default;
        _capturedProperties = null;
    }

    /// <summary>
    /// Appends a literal text segment of the interpolated string to the message.
    /// </summary>
    /// <param name="value">The literal text to append.</param>
    public void AppendLiteral(string value) => _handler.AppendLiteral(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    public void AppendFormatted<T>(T value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            LogPropertyDestructuring.AppendDestructured(ref _handler, value);
        else
            _handler.AppendFormatted(value, tag.Format);
    }

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted<T>(T value, int alignment) => _handler.AppendFormatted(value, alignment);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, int alignment, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            _handler.AppendFormatted(LogPropertyDestructuring.Render(value), alignment);
        else
            _handler.AppendFormatted(value, alignment, tag.Format);
    }

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    public void AppendFormatted(string? value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted(string? value, int alignment) => _handler.AppendFormatted(value, alignment);

    internal string ToStringAndClear() => _handler.ToStringAndClear();

    internal IReadOnlyList<KeyValuePair<string, object?>> GetCapturedProperties() =>
        _capturedProperties ?? (IReadOnlyList<KeyValuePair<string, object?>>)[];
}

/// <summary>
/// Interpolated string handler for the message parameter of the <see cref="StructuredLoggerExtensions"/> Write methods. Building the message is skipped when the specified level is not enabled for the target <see cref="ILogger"/>. A format starting with an <c>&lt;PropertyName&gt;</c> tag also captures that interpolated value as a structured property named <c>PropertyName</c>; any remaining format text after the tag is used to format the value in the message. An empty tag (<c>&lt;&gt;</c>) opts out of capturing while still allowing the remaining format to start with '&lt;'. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
/// </summary>
[InterpolatedStringHandler]
public ref struct WriteInterpolatedStringHandler
{
    private DefaultInterpolatedStringHandler _handler;
    private List<KeyValuePair<string, object?>>? _capturedProperties;
    internal readonly bool IsEnabled;

    /// <summary>
    /// Initializes the handler and checks whether <paramref name="level"/> is enabled for <paramref name="logger"/>.
    /// </summary>
    /// <param name="literalLength">The total number of characters in the interpolated string's literal text.</param>
    /// <param name="formattedCount">The number of interpolation expressions in the interpolated string.</param>
    /// <param name="logger">The logger the message is being built for.</param>
    /// <param name="level">The severity level the message is being built for.</param>
    /// <param name="handlerIsValid">Set to <see langword="false"/> when <paramref name="level"/> is not enabled for <paramref name="logger"/>, so the compiler skips evaluating and appending the interpolated string's arguments.</param>
    public WriteInterpolatedStringHandler(int literalLength, int formattedCount, ILogger logger, LogLevel level, out bool handlerIsValid)
    {
        IsEnabled = handlerIsValid = logger.IsEnabled(level);
        _handler = handlerIsValid
            ? new DefaultInterpolatedStringHandler(literalLength, formattedCount, CultureInfo.InvariantCulture)
            : default;
        _capturedProperties = null;
    }

    /// <summary>
    /// Appends a literal text segment of the interpolated string to the message.
    /// </summary>
    /// <param name="value">The literal text to append.</param>
    public void AppendLiteral(string value) => _handler.AppendLiteral(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    public void AppendFormatted<T>(T value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            LogPropertyDestructuring.AppendDestructured(ref _handler, value);
        else
            _handler.AppendFormatted(value, tag.Format);
    }

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted<T>(T value, int alignment) => _handler.AppendFormatted(value, alignment);

    /// <summary>
    /// Appends the formatted value of an interpolation expression to the message. If <paramref name="format"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name="value"/> is also captured as a structured property. A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref="IFormattable"/>/<see cref="object.ToString"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.
    /// </summary>
    /// <typeparam name="T">The type of the value to append.</typeparam>
    /// <param name="value">The value to format and append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    /// <param name="format">A standard or custom format string supported by <paramref name="value"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag.</param>
    public void AppendFormatted<T>(T value, int alignment, string? format)
    {
        TagFormat tag = LogPropertyTagFormat.Parse(format);
        if (tag.PropertyName is not null)
        {
            // Capacity 2: a message that captures anything almost always captures one or two
            // properties, and both fit without List's default 4-slot first allocation.
            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);
            _capturedProperties.Add(new(tag.PropertyName, value));
        }

        if (tag.Destructure && tag.Format is null)
            _handler.AppendFormatted(LogPropertyDestructuring.Render(value), alignment);
        else
            _handler.AppendFormatted(value, alignment, tag.Format);
    }

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    public void AppendFormatted(string? value) => _handler.AppendFormatted(value);

    /// <summary>
    /// Appends a string interpolation value to the message.
    /// </summary>
    /// <param name="value">The string to append.</param>
    /// <param name="alignment">The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.</param>
    public void AppendFormatted(string? value, int alignment) => _handler.AppendFormatted(value, alignment);

    internal string ToStringAndClear() => _handler.ToStringAndClear();

    internal IReadOnlyList<KeyValuePair<string, object?>> GetCapturedProperties() =>
        _capturedProperties ?? (IReadOnlyList<KeyValuePair<string, object?>>)[];
}
