// <auto-generated/>
#nullable enable
using System.Collections;

namespace RandomSkunk.StructuredLogging;

/// <summary>
/// Logger state for the 1-property generic structured-logging overloads. Combines the properties
/// explicitly passed by the caller with any the message's interpolated string handler captured via
/// &lt;PropertyName&gt; format tags.
/// </summary>
internal readonly struct LogPropertiesState<T1> : IReadOnlyList<KeyValuePair<string, object?>>
{
    public static readonly Func<LogPropertiesState<T1>, Exception?, string> Formatter = static (state, _) => state._message;

    private readonly string _message;
    private readonly IReadOnlyList<KeyValuePair<string, object?>> _explicitProperties;
    private readonly string _name1;
    private readonly T1 _value1;

    public LogPropertiesState(string message, IReadOnlyList<KeyValuePair<string, object?>> explicitProperties, (string Name, T1 Value) property1)
    {
        _message = message;
        _explicitProperties = explicitProperties;
        _name1 = property1.Name;
        _value1 = property1.Value;
    }

    public int Count => _explicitProperties.Count + 1;

    public KeyValuePair<string, object?> this[int index]
    {
        get
        {
            if (index < _explicitProperties.Count)
                return _explicitProperties[index];

            return (index - _explicitProperties.Count) switch
            {
                0 => new(_name1, _value1),
                _ => throw new ArgumentOutOfRangeException(nameof(index)),
            };
        }
    }

    public override string ToString() => _message;

    public IEnumerator<KeyValuePair<string, object?>> GetEnumerator()
    {
        for (int i = 0; i < Count; i++)
            yield return this[i];
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}

/// <summary>
/// Logger state for the 2-property generic structured-logging overloads. Combines the properties
/// explicitly passed by the caller with any the message's interpolated string handler captured via
/// &lt;PropertyName&gt; format tags.
/// </summary>
internal readonly struct LogPropertiesState<T1, T2> : IReadOnlyList<KeyValuePair<string, object?>>
{
    public static readonly Func<LogPropertiesState<T1, T2>, Exception?, string> Formatter = static (state, _) => state._message;

    private readonly string _message;
    private readonly IReadOnlyList<KeyValuePair<string, object?>> _explicitProperties;
    private readonly string _name1;
    private readonly T1 _value1;
    private readonly string _name2;
    private readonly T2 _value2;

    public LogPropertiesState(string message, IReadOnlyList<KeyValuePair<string, object?>> explicitProperties, (string Name, T1 Value) property1, (string Name, T2 Value) property2)
    {
        _message = message;
        _explicitProperties = explicitProperties;
        _name1 = property1.Name;
        _value1 = property1.Value;
        _name2 = property2.Name;
        _value2 = property2.Value;
    }

    public int Count => _explicitProperties.Count + 2;

    public KeyValuePair<string, object?> this[int index]
    {
        get
        {
            if (index < _explicitProperties.Count)
                return _explicitProperties[index];

            return (index - _explicitProperties.Count) switch
            {
                0 => new(_name1, _value1),
                1 => new(_name2, _value2),
                _ => throw new ArgumentOutOfRangeException(nameof(index)),
            };
        }
    }

    public override string ToString() => _message;

    public IEnumerator<KeyValuePair<string, object?>> GetEnumerator()
    {
        for (int i = 0; i < Count; i++)
            yield return this[i];
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}

/// <summary>
/// Logger state for the 3-property generic structured-logging overloads. Combines the properties
/// explicitly passed by the caller with any the message's interpolated string handler captured via
/// &lt;PropertyName&gt; format tags.
/// </summary>
internal readonly struct LogPropertiesState<T1, T2, T3> : IReadOnlyList<KeyValuePair<string, object?>>
{
    public static readonly Func<LogPropertiesState<T1, T2, T3>, Exception?, string> Formatter = static (state, _) => state._message;

    private readonly string _message;
    private readonly IReadOnlyList<KeyValuePair<string, object?>> _explicitProperties;
    private readonly string _name1;
    private readonly T1 _value1;
    private readonly string _name2;
    private readonly T2 _value2;
    private readonly string _name3;
    private readonly T3 _value3;

    public LogPropertiesState(string message, IReadOnlyList<KeyValuePair<string, object?>> explicitProperties, (string Name, T1 Value) property1, (string Name, T2 Value) property2, (string Name, T3 Value) property3)
    {
        _message = message;
        _explicitProperties = explicitProperties;
        _name1 = property1.Name;
        _value1 = property1.Value;
        _name2 = property2.Name;
        _value2 = property2.Value;
        _name3 = property3.Name;
        _value3 = property3.Value;
    }

    public int Count => _explicitProperties.Count + 3;

    public KeyValuePair<string, object?> this[int index]
    {
        get
        {
            if (index < _explicitProperties.Count)
                return _explicitProperties[index];

            return (index - _explicitProperties.Count) switch
            {
                0 => new(_name1, _value1),
                1 => new(_name2, _value2),
                2 => new(_name3, _value3),
                _ => throw new ArgumentOutOfRangeException(nameof(index)),
            };
        }
    }

    public override string ToString() => _message;

    public IEnumerator<KeyValuePair<string, object?>> GetEnumerator()
    {
        for (int i = 0; i < Count; i++)
            yield return this[i];
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}

/// <summary>
/// Logger state for the 4-property generic structured-logging overloads. Combines the properties
/// explicitly passed by the caller with any the message's interpolated string handler captured via
/// &lt;PropertyName&gt; format tags.
/// </summary>
internal readonly struct LogPropertiesState<T1, T2, T3, T4> : IReadOnlyList<KeyValuePair<string, object?>>
{
    public static readonly Func<LogPropertiesState<T1, T2, T3, T4>, Exception?, string> Formatter = static (state, _) => state._message;

    private readonly string _message;
    private readonly IReadOnlyList<KeyValuePair<string, object?>> _explicitProperties;
    private readonly string _name1;
    private readonly T1 _value1;
    private readonly string _name2;
    private readonly T2 _value2;
    private readonly string _name3;
    private readonly T3 _value3;
    private readonly string _name4;
    private readonly T4 _value4;

    public LogPropertiesState(string message, IReadOnlyList<KeyValuePair<string, object?>> explicitProperties, (string Name, T1 Value) property1, (string Name, T2 Value) property2, (string Name, T3 Value) property3, (string Name, T4 Value) property4)
    {
        _message = message;
        _explicitProperties = explicitProperties;
        _name1 = property1.Name;
        _value1 = property1.Value;
        _name2 = property2.Name;
        _value2 = property2.Value;
        _name3 = property3.Name;
        _value3 = property3.Value;
        _name4 = property4.Name;
        _value4 = property4.Value;
    }

    public int Count => _explicitProperties.Count + 4;

    public KeyValuePair<string, object?> this[int index]
    {
        get
        {
            if (index < _explicitProperties.Count)
                return _explicitProperties[index];

            return (index - _explicitProperties.Count) switch
            {
                0 => new(_name1, _value1),
                1 => new(_name2, _value2),
                2 => new(_name3, _value3),
                3 => new(_name4, _value4),
                _ => throw new ArgumentOutOfRangeException(nameof(index)),
            };
        }
    }

    public override string ToString() => _message;

    public IEnumerator<KeyValuePair<string, object?>> GetEnumerator()
    {
        for (int i = 0; i < Count; i++)
            yield return this[i];
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}

/// <summary>
/// Logger state for the 5-property generic structured-logging overloads. Combines the properties
/// explicitly passed by the caller with any the message's interpolated string handler captured via
/// &lt;PropertyName&gt; format tags.
/// </summary>
internal readonly struct LogPropertiesState<T1, T2, T3, T4, T5> : IReadOnlyList<KeyValuePair<string, object?>>
{
    public static readonly Func<LogPropertiesState<T1, T2, T3, T4, T5>, Exception?, string> Formatter = static (state, _) => state._message;

    private readonly string _message;
    private readonly IReadOnlyList<KeyValuePair<string, object?>> _explicitProperties;
    private readonly string _name1;
    private readonly T1 _value1;
    private readonly string _name2;
    private readonly T2 _value2;
    private readonly string _name3;
    private readonly T3 _value3;
    private readonly string _name4;
    private readonly T4 _value4;
    private readonly string _name5;
    private readonly T5 _value5;

    public LogPropertiesState(string message, IReadOnlyList<KeyValuePair<string, object?>> explicitProperties, (string Name, T1 Value) property1, (string Name, T2 Value) property2, (string Name, T3 Value) property3, (string Name, T4 Value) property4, (string Name, T5 Value) property5)
    {
        _message = message;
        _explicitProperties = explicitProperties;
        _name1 = property1.Name;
        _value1 = property1.Value;
        _name2 = property2.Name;
        _value2 = property2.Value;
        _name3 = property3.Name;
        _value3 = property3.Value;
        _name4 = property4.Name;
        _value4 = property4.Value;
        _name5 = property5.Name;
        _value5 = property5.Value;
    }

    public int Count => _explicitProperties.Count + 5;

    public KeyValuePair<string, object?> this[int index]
    {
        get
        {
            if (index < _explicitProperties.Count)
                return _explicitProperties[index];

            return (index - _explicitProperties.Count) switch
            {
                0 => new(_name1, _value1),
                1 => new(_name2, _value2),
                2 => new(_name3, _value3),
                3 => new(_name4, _value4),
                4 => new(_name5, _value5),
                _ => throw new ArgumentOutOfRangeException(nameof(index)),
            };
        }
    }

    public override string ToString() => _message;

    public IEnumerator<KeyValuePair<string, object?>> GetEnumerator()
    {
        for (int i = 0; i < Count; i++)
            yield return this[i];
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}

/// <summary>
/// Logger state for the 6-property generic structured-logging overloads. Combines the properties
/// explicitly passed by the caller with any the message's interpolated string handler captured via
/// &lt;PropertyName&gt; format tags.
/// </summary>
internal readonly struct LogPropertiesState<T1, T2, T3, T4, T5, T6> : IReadOnlyList<KeyValuePair<string, object?>>
{
    public static readonly Func<LogPropertiesState<T1, T2, T3, T4, T5, T6>, Exception?, string> Formatter = static (state, _) => state._message;

    private readonly string _message;
    private readonly IReadOnlyList<KeyValuePair<string, object?>> _explicitProperties;
    private readonly string _name1;
    private readonly T1 _value1;
    private readonly string _name2;
    private readonly T2 _value2;
    private readonly string _name3;
    private readonly T3 _value3;
    private readonly string _name4;
    private readonly T4 _value4;
    private readonly string _name5;
    private readonly T5 _value5;
    private readonly string _name6;
    private readonly T6 _value6;

    public LogPropertiesState(string message, IReadOnlyList<KeyValuePair<string, object?>> explicitProperties, (string Name, T1 Value) property1, (string Name, T2 Value) property2, (string Name, T3 Value) property3, (string Name, T4 Value) property4, (string Name, T5 Value) property5, (string Name, T6 Value) property6)
    {
        _message = message;
        _explicitProperties = explicitProperties;
        _name1 = property1.Name;
        _value1 = property1.Value;
        _name2 = property2.Name;
        _value2 = property2.Value;
        _name3 = property3.Name;
        _value3 = property3.Value;
        _name4 = property4.Name;
        _value4 = property4.Value;
        _name5 = property5.Name;
        _value5 = property5.Value;
        _name6 = property6.Name;
        _value6 = property6.Value;
    }

    public int Count => _explicitProperties.Count + 6;

    public KeyValuePair<string, object?> this[int index]
    {
        get
        {
            if (index < _explicitProperties.Count)
                return _explicitProperties[index];

            return (index - _explicitProperties.Count) switch
            {
                0 => new(_name1, _value1),
                1 => new(_name2, _value2),
                2 => new(_name3, _value3),
                3 => new(_name4, _value4),
                4 => new(_name5, _value5),
                5 => new(_name6, _value6),
                _ => throw new ArgumentOutOfRangeException(nameof(index)),
            };
        }
    }

    public override string ToString() => _message;

    public IEnumerator<KeyValuePair<string, object?>> GetEnumerator()
    {
        for (int i = 0; i < Count; i++)
            yield return this[i];
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
