// Regenerates the mechanically-repetitive parts of the library's public API:
// the interpolated string handlers, the generic property-arity state structs,
// and the full LoggerExtensions overload set.
//
// Run from the repo root: dotnet run eng/GenerateSource.cs

using System.Text;

const int MaxArity = 6;
string[] levels = ["Trace", "Debug", "Information", "Warning", "Error", "Critical"];

string outputDir = Path.Combine(Directory.GetCurrentDirectory(), "src", "RandomSkunk.StructuredLogging");
Directory.CreateDirectory(outputDir);

File.WriteAllText(Path.Combine(outputDir, "LogInterpolatedStringHandlers.g.cs"), GenerateHandlers(levels));
File.WriteAllText(Path.Combine(outputDir, "LogPropertiesState.g.cs"), GenerateGenericStates(MaxArity));
File.WriteAllText(Path.Combine(outputDir, "StructuredLoggerExtensions.g.cs"), GenerateExtensionMethods(levels, MaxArity));

Console.WriteLine($"Generated files written to {outputDir}");

static string Ordinal(int n) => n switch
{
    1 => "first",
    2 => "second",
    3 => "third",
    4 => "fourth",
    5 => "fifth",
    6 => "sixth",
    _ => $"{n}th",
};

static string NumberWord(int n) => n switch
{
    1 => "one",
    2 => "two",
    3 => "three",
    4 => "four",
    5 => "five",
    6 => "six",
    _ => n.ToString(),
};

static void WriteDocComment(
    StringBuilder sb,
    string indent,
    string summary,
    IEnumerable<(string Name, string Text)>? typeParams = null,
    IEnumerable<(string Name, string Text)>? parameters = null)
{
    sb.AppendLine($"{indent}/// <summary>");
    sb.AppendLine($"{indent}/// {summary}");
    sb.AppendLine($"{indent}/// </summary>");

    if (typeParams is not null)
        foreach ((string name, string text) in typeParams)
            sb.AppendLine($"{indent}/// <typeparam name=\"{name}\">{text}</typeparam>");

    if (parameters is not null)
        foreach ((string name, string text) in parameters)
            sb.AppendLine($"{indent}/// <param name=\"{name}\">{text}</param>");
}

static string GenerateHandlers(string[] levels)
{
    StringBuilder sb = new();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using System.Globalization;");
    sb.AppendLine("using System.Runtime.CompilerServices;");
    sb.AppendLine("using Microsoft.Extensions.Logging;");
    sb.AppendLine();
    sb.AppendLine("namespace RandomSkunk.StructuredLogging;");
    sb.AppendLine();

    foreach (string level in levels)
    {
        AppendHandler(sb, $"{level}InterpolatedStringHandler", level);
        sb.AppendLine();
    }

    AppendHandler(sb, "WriteInterpolatedStringHandler", null);

    return sb.ToString();
}

static void AppendHandler(StringBuilder sb, string typeName, string? fixedLevel)
{
    string ctorParams = fixedLevel is not null
        ? "int literalLength, int formattedCount, ILogger logger, out bool handlerIsValid"
        : "int literalLength, int formattedCount, ILogger logger, LogLevel level, out bool handlerIsValid";

    string enabledCheck = fixedLevel is not null
        ? $"logger.IsEnabled(LogLevel.{fixedLevel})"
        : "logger.IsEnabled(level)";

    const string destructureDoc = " A tag whose name starts with <c>@</c> (e.g. <c>&lt;@PropertyName&gt;</c> or <c>&lt;@&gt;</c>) requests Serilog-style destructured capture. If no format follows the tag, the value is also rendered into the message using destructured formatting instead of <see cref=\"IFormattable\"/>/<see cref=\"object.ToString\"/> formatting; if a format does follow the tag, that format is honored for the message exactly like an ordinary tag, and destructuring only affects how the property is captured. Either way, a captured property name is prefixed with <c>@</c> (e.g. <c>@PropertyName</c>) to signal the destructuring request downstream; the captured value itself is always the raw, undestructured value.";

    string typeSummary = fixedLevel is not null
        ? $"Interpolated string handler for the message parameter of the {fixedLevel}-level <see cref=\"StructuredLoggerExtensions\"/> methods. Building the message is skipped when the {fixedLevel} level is not enabled for the target <see cref=\"ILogger\"/>. A format starting with an <c>&lt;PropertyName&gt;</c> tag also captures that interpolated value as a structured property named <c>PropertyName</c>; any remaining format text after the tag is used to format the value in the message. An empty tag (<c>&lt;&gt;</c>) opts out of capturing while still allowing the remaining format to start with '&lt;'.{destructureDoc}"
        : $"Interpolated string handler for the message parameter of the <see cref=\"StructuredLoggerExtensions\"/> Write methods. Building the message is skipped when the specified level is not enabled for the target <see cref=\"ILogger\"/>. A format starting with an <c>&lt;PropertyName&gt;</c> tag also captures that interpolated value as a structured property named <c>PropertyName</c>; any remaining format text after the tag is used to format the value in the message. An empty tag (<c>&lt;&gt;</c>) opts out of capturing while still allowing the remaining format to start with '&lt;'.{destructureDoc}";

    string ctorSummary = fixedLevel is not null
        ? $"Initializes the handler and checks whether the {fixedLevel} level is enabled for <paramref name=\"logger\"/>."
        : "Initializes the handler and checks whether <paramref name=\"level\"/> is enabled for <paramref name=\"logger\"/>.";

    string handlerIsValidDoc = fixedLevel is not null
        ? $"Set to <see langword=\"false\"/> when the {fixedLevel} level is not enabled for <paramref name=\"logger\"/>, so the compiler skips evaluating and appending the interpolated string's arguments."
        : "Set to <see langword=\"false\"/> when <paramref name=\"level\"/> is not enabled for <paramref name=\"logger\"/>, so the compiler skips evaluating and appending the interpolated string's arguments.";

    List<(string, string)> ctorParamDocs = new()
    {
        ("literalLength", "The total number of characters in the interpolated string's literal text."),
        ("formattedCount", "The number of interpolation expressions in the interpolated string."),
        ("logger", "The logger the message is being built for."),
    };

    if (fixedLevel is null)
        ctorParamDocs.Add(("level", "The severity level the message is being built for."));

    ctorParamDocs.Add(("handlerIsValid", handlerIsValidDoc));

    const string alignmentDoc = "The minimum number of characters the formatted value should occupy in the message; positive values right-align with padding, negative values left-align with padding.";

    // DefaultInterpolatedStringHandler is a ref struct (it's backed by a pooled Span<char>
    // buffer), so this wrapper must be a ref struct too, and it can't be readonly: readonly
    // struct fields of mutable-struct type get defensive-copied on every method call, which
    // would silently make Append* calls mutate a throwaway copy instead of `_handler`.
    WriteDocComment(sb, string.Empty, typeSummary);
    sb.AppendLine("[InterpolatedStringHandler]");
    sb.AppendLine($"public ref struct {typeName}");
    sb.AppendLine("{");
    sb.AppendLine("    private DefaultInterpolatedStringHandler _handler;");
    sb.AppendLine("    private List<KeyValuePair<string, object?>>? _capturedProperties;");
    sb.AppendLine("    internal readonly bool IsEnabled;");
    sb.AppendLine();
    WriteDocComment(sb, "    ", ctorSummary, parameters: ctorParamDocs);
    sb.AppendLine($"    public {typeName}({ctorParams})");
    sb.AppendLine("    {");
    sb.AppendLine($"        IsEnabled = handlerIsValid = {enabledCheck};");
    sb.AppendLine("        _handler = handlerIsValid");
    sb.AppendLine("            ? new DefaultInterpolatedStringHandler(literalLength, formattedCount, CultureInfo.InvariantCulture)");
    sb.AppendLine("            : default;");
    sb.AppendLine("        _capturedProperties = null;");
    sb.AppendLine("    }");
    sb.AppendLine();
    WriteDocComment(
        sb,
        "    ",
        "Appends a literal text segment of the interpolated string to the message.",
        parameters: [("value", "The literal text to append.")]);
    sb.AppendLine("    public void AppendLiteral(string value) => _handler.AppendLiteral(value);");
    sb.AppendLine();
    WriteDocComment(
        sb,
        "    ",
        "Appends the formatted value of an interpolation expression to the message.",
        typeParams: [("T", "The type of the value to append.")],
        parameters: [("value", "The value to format and append.")]);
    sb.AppendLine("    public void AppendFormatted<T>(T value) => _handler.AppendFormatted(value);");
    sb.AppendLine();
    WriteDocComment(
        sb,
        "    ",
        $"Appends the formatted value of an interpolation expression to the message. If <paramref name=\"format\"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name=\"value\"/> is also captured as a structured property.{destructureDoc}",
        typeParams: [("T", "The type of the value to append.")],
        parameters:
        [
            ("value", "The value to format and append."),
            ("format", "A standard or custom format string supported by <paramref name=\"value\"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag."),
        ]);
    sb.AppendLine("    public void AppendFormatted<T>(T value, string? format)");
    sb.AppendLine("    {");
    sb.AppendLine("        TagFormat tag = LogPropertyTagFormat.Parse(format);");
    sb.AppendLine("        if (tag.PropertyName is not null)");
    // Capacity 2, not List's default growth: a message that captures at all almost always captures one
    // or two properties, and both fit without the default's 4-slot first allocation. Three or more pays
    // for the abandoned 2-slot array, which the far greater frequency of the one/two cases outweighs.
    sb.AppendLine("        {");
    sb.AppendLine("            // Capacity 2: a message that captures anything almost always captures one or two");
    sb.AppendLine("            // properties, and both fit without List's default 4-slot first allocation.");
    sb.AppendLine("            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);");
    sb.AppendLine("            _capturedProperties.Add(new(tag.PropertyName, value));");
    sb.AppendLine("        }");
    sb.AppendLine();
    sb.AppendLine("        if (tag.Destructure && tag.Format is null)");
    sb.AppendLine("            LogPropertyDestructuring.AppendDestructured(ref _handler, value);");
    sb.AppendLine("        else");
    sb.AppendLine("            _handler.AppendFormatted(value, tag.Format);");
    sb.AppendLine("    }");
    sb.AppendLine();
    WriteDocComment(
        sb,
        "    ",
        "Appends the formatted value of an interpolation expression to the message.",
        typeParams: [("T", "The type of the value to append.")],
        parameters:
        [
            ("value", "The value to format and append."),
            ("alignment", alignmentDoc),
        ]);
    sb.AppendLine("    public void AppendFormatted<T>(T value, int alignment) => _handler.AppendFormatted(value, alignment);");
    sb.AppendLine();
    WriteDocComment(
        sb,
        "    ",
        $"Appends the formatted value of an interpolation expression to the message. If <paramref name=\"format\"/> starts with an <c>&lt;PropertyName&gt;</c> tag, <paramref name=\"value\"/> is also captured as a structured property.{destructureDoc}",
        typeParams: [("T", "The type of the value to append.")],
        parameters:
        [
            ("value", "The value to format and append."),
            ("alignment", alignmentDoc),
            ("format", "A standard or custom format string supported by <paramref name=\"value\"/>'s type, optionally preceded by a <c>&lt;PropertyName&gt;</c> capture tag."),
        ]);
    sb.AppendLine("    public void AppendFormatted<T>(T value, int alignment, string? format)");
    sb.AppendLine("    {");
    sb.AppendLine("        TagFormat tag = LogPropertyTagFormat.Parse(format);");
    sb.AppendLine("        if (tag.PropertyName is not null)");
    // Capacity 2, not List's default growth: a message that captures at all almost always captures one
    // or two properties, and both fit without the default's 4-slot first allocation. Three or more pays
    // for the abandoned 2-slot array, which the far greater frequency of the one/two cases outweighs.
    sb.AppendLine("        {");
    sb.AppendLine("            // Capacity 2: a message that captures anything almost always captures one or two");
    sb.AppendLine("            // properties, and both fit without List's default 4-slot first allocation.");
    sb.AppendLine("            _capturedProperties ??= new List<KeyValuePair<string, object?>>(2);");
    sb.AppendLine("            _capturedProperties.Add(new(tag.PropertyName, value));");
    sb.AppendLine("        }");
    sb.AppendLine();
    // Unlike the non-aligned overload above, this one can't use AppendDestructured: padding the rendered
    // text to `alignment` needs it as a single contiguous string, so the intermediate Render() allocation
    // is unavoidable here. Rendering into an alignment is a rare enough combination not to warrant
    // hand-rolling the padding around a chunk-by-chunk append.
    sb.AppendLine("        if (tag.Destructure && tag.Format is null)");
    sb.AppendLine("            _handler.AppendFormatted(LogPropertyDestructuring.Render(value), alignment);");
    sb.AppendLine("        else");
    sb.AppendLine("            _handler.AppendFormatted(value, alignment, tag.Format);");
    sb.AppendLine("    }");
    sb.AppendLine();
    WriteDocComment(
        sb,
        "    ",
        "Appends a string interpolation value to the message.",
        parameters: [("value", "The string to append.")]);
    sb.AppendLine("    public void AppendFormatted(string? value) => _handler.AppendFormatted(value);");
    sb.AppendLine();
    WriteDocComment(
        sb,
        "    ",
        "Appends a string interpolation value to the message.",
        parameters:
        [
            ("value", "The string to append."),
            ("alignment", alignmentDoc),
        ]);
    sb.AppendLine("    public void AppendFormatted(string? value, int alignment) => _handler.AppendFormatted(value, alignment);");
    sb.AppendLine();
    sb.AppendLine("    internal string ToStringAndClear() => _handler.ToStringAndClear();");
    sb.AppendLine();
    sb.AppendLine("    internal IReadOnlyList<KeyValuePair<string, object?>> GetCapturedProperties() =>");
    sb.AppendLine("        _capturedProperties ?? (IReadOnlyList<KeyValuePair<string, object?>>)[];");
    sb.AppendLine("}");
}

static string GenerateGenericStates(int maxArity)
{
    StringBuilder sb = new();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using System.Collections;");
    sb.AppendLine();
    sb.AppendLine("namespace RandomSkunk.StructuredLogging;");
    sb.AppendLine();

    for (int arity = 1; arity <= maxArity; arity++)
    {
        AppendGenericState(sb, arity);
        if (arity < maxArity)
            sb.AppendLine();
    }

    return sb.ToString();
}

static void AppendGenericState(StringBuilder sb, int arity)
{
    string typeParams = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"));
    string ctorParams = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"(string Name, T{i} Value) property{i}"));

    sb.AppendLine("/// <summary>");
    sb.AppendLine($"/// Logger state for the {arity}-property generic structured-logging overloads. Combines the properties");
    sb.AppendLine("/// explicitly passed by the caller with any the message's interpolated string handler captured via");
    sb.AppendLine("/// &lt;PropertyName&gt; format tags.");
    sb.AppendLine("/// </summary>");
    sb.AppendLine($"internal readonly struct LogPropertiesState<{typeParams}> : IReadOnlyList<KeyValuePair<string, object?>>");
    sb.AppendLine("{");
    sb.AppendLine($"    public static readonly Func<LogPropertiesState<{typeParams}>, Exception?, string> Formatter = static (state, _) => state._message;");
    sb.AppendLine();
    sb.AppendLine("    private readonly string _message;");
    sb.AppendLine("    private readonly IReadOnlyList<KeyValuePair<string, object?>> _logProperties;");
    sb.AppendLine("    private readonly IReadOnlyList<KeyValuePair<string, object?>> _capturedProperties;");

    foreach (int i in Enumerable.Range(1, arity))
    {
        sb.AppendLine($"    private readonly string _name{i};");
        sb.AppendLine($"    private readonly T{i} _value{i};");
    }

    sb.AppendLine();
    sb.AppendLine($"    public LogPropertiesState(string message, IReadOnlyList<KeyValuePair<string, object?>> logProperties, IReadOnlyList<KeyValuePair<string, object?>> capturedProperties, {ctorParams})");
    sb.AppendLine("    {");
    sb.AppendLine("        _message = message;");
    sb.AppendLine("        _logProperties = logProperties;");
    sb.AppendLine("        _capturedProperties = capturedProperties;");

    foreach (int i in Enumerable.Range(1, arity))
    {
        sb.AppendLine($"        _name{i} = property{i}.Name;");
        sb.AppendLine($"        _value{i} = property{i}.Value;");
    }

    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine($"    public int Count => _logProperties.Count + _capturedProperties.Count + {arity};");
    sb.AppendLine();
    sb.AppendLine("    public KeyValuePair<string, object?> this[int index]");
    sb.AppendLine("    {");
    sb.AppendLine("        get");
    sb.AppendLine("        {");
    sb.AppendLine("            if (index < _logProperties.Count)");
    sb.AppendLine("                return _logProperties[index];");
    sb.AppendLine();
    sb.AppendLine("            index -= _logProperties.Count;");
    sb.AppendLine();
    sb.AppendLine("            if (index < _capturedProperties.Count)");
    sb.AppendLine("                return _capturedProperties[index];");
    sb.AppendLine();
    sb.AppendLine("            return (index - _capturedProperties.Count) switch");
    sb.AppendLine("            {");

    foreach (int i in Enumerable.Range(1, arity))
        sb.AppendLine($"                {i - 1} => new(_name{i}, _value{i}),");

    sb.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(index)),");
    sb.AppendLine("            };");
    sb.AppendLine("        }");
    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine("    public override string ToString() => _message;");
    sb.AppendLine();
    sb.AppendLine("    public IEnumerator<KeyValuePair<string, object?>> GetEnumerator()");
    sb.AppendLine("    {");
    sb.AppendLine("        for (int i = 0; i < Count; i++)");
    sb.AppendLine("            yield return this[i];");
    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine("    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();");
    sb.AppendLine("}");
}

static string GenerateExtensionMethods(string[] levels, int maxArity)
{
    MethodGroup[] groups = levels
        .Select(level => new MethodGroup(level, $"{level}InterpolatedStringHandler", $"LogLevel.{level}", ["logger"], null))
        .Append(new MethodGroup("Write", "WriteInterpolatedStringHandler", "level", ["logger", "level"], "LogLevel level"))
        .ToArray();

    Combo[] combos =
    [
        new(["EventId eventId", "Exception? exception"], "eventId", "exception"),
        new(["EventId eventId"], "eventId", "null"),
        new(["Exception? exception"], "default", "exception"),
        new([], "default", "null"),
    ];

    StringBuilder sb = new();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using System.Runtime.CompilerServices;");
    sb.AppendLine("using Microsoft.Extensions.Logging;");
    sb.AppendLine();
    sb.AppendLine("namespace RandomSkunk.StructuredLogging;");
    sb.AppendLine();
    sb.AppendLine("/// <summary>");
    sb.AppendLine("/// Structured-logging extension methods for <see cref=\"ILogger\"/>.");
    sb.AppendLine("/// </summary>");
    sb.AppendLine("public static class StructuredLoggerExtensions");
    sb.AppendLine("{");

    bool first = true;
    foreach (MethodGroup group in groups)
    {
        foreach (Combo combo in combos)
        {
            foreach (bool useHandler in new[] { true, false })
            {
                for (int arity = 0; arity <= maxArity; arity++)
                {
                    if (!first)
                        sb.AppendLine();
                    first = false;
                    AppendArityMethod(sb, group, combo, arity, includeCollection: false, useHandler);
                }

                for (int arity = 0; arity <= maxArity; arity++)
                {
                    sb.AppendLine();
                    AppendArityMethod(sb, group, combo, arity, includeCollection: true, useHandler);
                }
            }
        }
    }

    sb.AppendLine("}");
    return sb.ToString();
}

static string HandlerAttribute(MethodGroup group) =>
    "[InterpolatedStringHandlerArgument(" + string.Join(", ", group.HandlerArgNames.Select(n => $"\"{n}\"")) + ")]";

static List<string> BaseParameters(MethodGroup group, Combo combo, bool includeCollection, bool useHandler)
{
    List<string> parameters = new() { "this ILogger logger" };
    if (includeCollection)
        parameters.Add("IReadOnlyCollection<KeyValuePair<string, object?>> logProperties");
    if (group.LevelParam is not null)
        parameters.Add(group.LevelParam);
    parameters.AddRange(combo.Params);
    parameters.Add(useHandler ? $"{HandlerAttribute(group)} ref {group.HandlerType} message" : "string message");
    return parameters;
}

static string LevelPhrase(MethodGroup group) => group.MethodName == "Write" ? "at the specified level" : $"at the {group.MethodName} level";

static string PropertyCountSummaryFragment(int arity) => arity switch
{
    0 => string.Empty,
    1 => " with one structured property",
    _ => $" with {NumberWord(arity)} structured properties",
};

static string CollectionSummaryFragment(int arity) => arity switch
{
    0 => " with a collection of structured properties",
    1 => " with a collection of structured properties and one additional structured property",
    _ => $" with a collection of structured properties and {NumberWord(arity)} additional structured properties",
};

static string MessageParamDoc(MethodGroup group, bool useHandler)
{
    if (!useHandler)
        return "The log message.";

    return group.MethodName == "Write"
        ? "The log message. Its interpolated arguments are only evaluated if <paramref name=\"level\"/> is enabled for <paramref name=\"logger\"/>."
        : $"The log message. Its interpolated arguments are only evaluated if the {group.MethodName} level is enabled for <paramref name=\"logger\"/>.";
}

static List<(string Name, string Text)> BaseParameterDocs(MethodGroup group, Combo combo, bool includeCollection, bool useHandler)
{
    List<(string, string)> docs = new() { ("logger", "The logger to write to.") };

    if (includeCollection)
        docs.Add(("logProperties", "A collection of structured log properties."));

    if (group.LevelParam is not null)
        docs.Add(("level", "The severity level of the log message."));

    if (combo.Params.Any(p => p.StartsWith("EventId")))
        docs.Add(("eventId", "The event id associated with the log message."));

    if (combo.Params.Any(p => p.StartsWith("Exception")))
        docs.Add(("exception", "The exception to associate with the log message."));

    docs.Add(("message", MessageParamDoc(group, useHandler)));
    return docs;
}

static void AppendMethodSignature(StringBuilder sb, string indent, string prefix, List<string> parameters)
{
    sb.AppendLine($"{indent}{prefix}(");

    for (int i = 0; i < parameters.Count; i++)
    {
        string suffix = i == parameters.Count - 1 ? ")" : ",";
        sb.AppendLine($"{indent}    {parameters[i]}{suffix}");
    }

    sb.AppendLine($"{indent}{{");
}

static void AppendArityMethod(StringBuilder sb, MethodGroup group, Combo combo, int arity, bool includeCollection, bool useHandler)
{
    string typeParamList = arity == 0 ? string.Empty : $"<{string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"))}>";
    string stateType = arity == 0 ? "LogPropertiesState" : $"LogPropertiesState<{string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"))}>";

    string propertyParamPrefix = includeCollection ? "additionalLogProperty" : "logProperty";

    List<string> parameters = BaseParameters(group, combo, includeCollection, useHandler);
    for (int i = 1; i <= arity; i++)
        parameters.Add($"(string Name, T{i} Value) {propertyParamPrefix}{i}");

    IEnumerable<(string, string)> typeParamDocs = Enumerable.Range(1, arity).Select(i => ($"T{i}", $"The type of the {Ordinal(i)} structured log property's value."));
    List<(string, string)> parameterDocs = BaseParameterDocs(group, combo, includeCollection, useHandler);
    string propertyDocFragment = includeCollection ? " additional" : "";
    foreach (int i in Enumerable.Range(1, arity))
        parameterDocs.Add(($"{propertyParamPrefix}{i}", $"The {Ordinal(i)}{propertyDocFragment} structured log property, as a name/value pair."));

    string summaryFragment = includeCollection ? CollectionSummaryFragment(arity) : PropertyCountSummaryFragment(arity);
    WriteDocComment(sb, "    ", $"Writes a log message{summaryFragment} {LevelPhrase(group)}.", typeParamDocs, parameterDocs);
    AppendMethodSignature(sb, "    ", $"public static void {group.MethodName}{typeParamList}", parameters);

    string messageTextExpr;
    string capturedPropertiesExpr;

    if (useHandler)
    {
        // ToStringAndClear() must run unconditionally: it returns the handler's rented buffer to
        // ArrayPool<char>.Shared, and skipping that when the level is disabled would leak the buffer.
        sb.AppendLine("        string messageText = message.ToStringAndClear();");
        sb.AppendLine();
        messageTextExpr = "messageText";
        capturedPropertiesExpr = "message.GetCapturedProperties()";
    }
    else
    {
        messageTextExpr = "message";
        capturedPropertiesExpr = "Array.Empty<KeyValuePair<string, object?>>()";
    }

    string enabledCheckExpr = useHandler ? "message.IsEnabled" : $"logger.IsEnabled({group.LevelExpr})";
    sb.AppendLine($"        if (!{enabledCheckExpr})");
    sb.AppendLine("            return;");
    sb.AppendLine();

    if (includeCollection)
        sb.AppendLine("        IReadOnlyList<KeyValuePair<string, object?>> logPropertiesList = logProperties as IReadOnlyList<KeyValuePair<string, object?>> ?? logProperties.ToArray();");

    string logPropertiesExpr = includeCollection ? "logPropertiesList" : "Array.Empty<KeyValuePair<string, object?>>()";

    if (arity == 0)
    {
        sb.AppendLine($"        {stateType} state = new({messageTextExpr}, {capturedPropertiesExpr}, {logPropertiesExpr});");
    }
    else
    {
        string propArgs = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"{propertyParamPrefix}{i}"));
        sb.AppendLine($"        {stateType} state = new({messageTextExpr}, {logPropertiesExpr}, {capturedPropertiesExpr}, {propArgs});");
    }

    sb.AppendLine($"        logger.Log({group.LevelExpr}, {combo.EventIdArg}, state, {combo.ExceptionArg}, {stateType}.Formatter);");
    sb.AppendLine("    }");
}

sealed record MethodGroup(string MethodName, string HandlerType, string LevelExpr, string[] HandlerArgNames, string? LevelParam);

sealed record Combo(string[] Params, string EventIdArg, string ExceptionArg);
