// Regenerates the mechanically-repetitive parts of the library's public API:
// the interpolated string handlers, the generic property-arity state structs,
// and the full LoggerExtensions overload set.
//
// Run from the repo root: dotnet run eng/GenerateSource.cs

using System.Text;

const int MaxArity = 6;
string[] levels = ["Trace", "Debug", "Information", "Warning", "Error", "Critical"];

var outputDir = Path.Combine(Directory.GetCurrentDirectory(), "src", "RandomSkunk.StructuredLogging", "Generated");
Directory.CreateDirectory(outputDir);

File.WriteAllText(Path.Combine(outputDir, "LogInterpolatedStringHandlers.g.cs"), GenerateHandlers(levels));
File.WriteAllText(Path.Combine(outputDir, "LogPropertiesState.g.cs"), GenerateGenericStates(MaxArity));
File.WriteAllText(Path.Combine(outputDir, "StructuredLoggerExtensions.g.cs"), GenerateExtensionMethods(levels, MaxArity));

Console.WriteLine($"Generated files written to {outputDir}");

static string GenerateHandlers(string[] levels)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using System.Globalization;");
    sb.AppendLine("using System.Runtime.CompilerServices;");
    sb.AppendLine("using Microsoft.Extensions.Logging;");
    sb.AppendLine();
    sb.AppendLine("namespace RandomSkunk.StructuredLogging;");
    sb.AppendLine();

    foreach (var level in levels)
    {
        AppendHandler(sb, $"{level}InterpolatedStringHandler", level);
        sb.AppendLine();
    }

    AppendHandler(sb, "LogInterpolatedStringHandler", null);

    return sb.ToString();
}

static void AppendHandler(StringBuilder sb, string typeName, string? fixedLevel)
{
    string ctorParams = fixedLevel is not null
        ? "int literalLength, int formattedCount, ILogger logger, out bool handlerIsValid"
        : "int literalLength, int formattedCount, ILogger logger, LogLevel level, out bool handlerIsValid";

    string enabledCheck = fixedLevel is not null
        ? $"logger.IsEnabled(LogLevel.{fixedLevel})"
        : "logger.IsEnabled(level)";

    // DefaultInterpolatedStringHandler is a ref struct (it's backed by a pooled Span<char>
    // buffer), so this wrapper must be a ref struct too, and it can't be readonly: readonly
    // struct fields of mutable-struct type get defensive-copied on every method call, which
    // would silently make Append* calls mutate a throwaway copy instead of `_handler`.
    sb.AppendLine("[InterpolatedStringHandler]");
    sb.AppendLine($"public ref struct {typeName}");
    sb.AppendLine("{");
    sb.AppendLine("    private DefaultInterpolatedStringHandler _handler;");
    sb.AppendLine();
    sb.AppendLine($"    public {typeName}({ctorParams})");
    sb.AppendLine("    {");
    sb.AppendLine($"        handlerIsValid = {enabledCheck};");
    sb.AppendLine("        _handler = handlerIsValid");
    sb.AppendLine("            ? new DefaultInterpolatedStringHandler(literalLength, formattedCount, CultureInfo.InvariantCulture)");
    sb.AppendLine("            : default;");
    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine($"    private {typeName}(string message)");
    sb.AppendLine("    {");
    sb.AppendLine("        _handler = new DefaultInterpolatedStringHandler(message.Length, 0, CultureInfo.InvariantCulture);");
    sb.AppendLine("        _handler.AppendLiteral(message);");
    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine($"    public static implicit operator {typeName}(string message) => new(message);");
    sb.AppendLine();
    sb.AppendLine("    public void AppendLiteral(string value) => _handler.AppendLiteral(value);");
    sb.AppendLine();
    sb.AppendLine("    public void AppendFormatted<T>(T value) => _handler.AppendFormatted(value);");
    sb.AppendLine();
    sb.AppendLine("    public void AppendFormatted<T>(T value, string? format) => _handler.AppendFormatted(value, format);");
    sb.AppendLine();
    sb.AppendLine("    public void AppendFormatted<T>(T value, int alignment) => _handler.AppendFormatted(value, alignment);");
    sb.AppendLine();
    sb.AppendLine("    public void AppendFormatted<T>(T value, int alignment, string? format) => _handler.AppendFormatted(value, alignment, format);");
    sb.AppendLine();
    sb.AppendLine("    public void AppendFormatted(string? value) => _handler.AppendFormatted(value);");
    sb.AppendLine();
    sb.AppendLine("    public void AppendFormatted(string? value, int alignment) => _handler.AppendFormatted(value, alignment);");
    sb.AppendLine();
    sb.AppendLine("    internal string GetFormattedText() => _handler.ToStringAndClear();");
    sb.AppendLine("}");
}

static string GenerateGenericStates(int maxArity)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using System.Collections;");
    sb.AppendLine();
    sb.AppendLine("namespace RandomSkunk.StructuredLogging;");
    sb.AppendLine();

    for (int arity = 1; arity <= maxArity; arity++)
    {
        AppendGenericState(sb, arity);
        if (arity < maxArity)
            sb.AppendLine();
    }

    return sb.ToString();
}

static void AppendGenericState(StringBuilder sb, int arity)
{
    var typeParams = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"));
    var ctorParams = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"(string Name, T{i} Value) property{i}"));

    sb.AppendLine("/// <summary>");
    sb.AppendLine($"/// Logger state for the {arity}-property generic structured-logging overloads.");
    sb.AppendLine("/// </summary>");
    sb.AppendLine($"internal readonly struct LogPropertiesState<{typeParams}> : IReadOnlyList<KeyValuePair<string, object?>>");
    sb.AppendLine("{");
    sb.AppendLine($"    public static readonly Func<LogPropertiesState<{typeParams}>, Exception?, string> Formatter = static (state, _) => state._message;");
    sb.AppendLine();
    sb.AppendLine("    private readonly string _message;");

    foreach (var i in Enumerable.Range(1, arity))
    {
        sb.AppendLine($"    private readonly string _name{i};");
        sb.AppendLine($"    private readonly T{i} _value{i};");
    }

    sb.AppendLine();
    sb.AppendLine($"    public LogPropertiesState(string message, {ctorParams})");
    sb.AppendLine("    {");
    sb.AppendLine("        _message = message;");

    foreach (var i in Enumerable.Range(1, arity))
    {
        sb.AppendLine($"        _name{i} = property{i}.Name;");
        sb.AppendLine($"        _value{i} = property{i}.Value;");
    }

    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine($"    public int Count => {arity};");
    sb.AppendLine();
    sb.AppendLine("    public KeyValuePair<string, object?> this[int index] => index switch");
    sb.AppendLine("    {");

    foreach (var i in Enumerable.Range(1, arity))
        sb.AppendLine($"        {i - 1} => new(_name{i}, _value{i}),");

    sb.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(index)),");
    sb.AppendLine("    };");
    sb.AppendLine();
    sb.AppendLine("    public override string ToString() => _message;");
    sb.AppendLine();
    sb.AppendLine("    public IEnumerator<KeyValuePair<string, object?>> GetEnumerator()");
    sb.AppendLine("    {");
    sb.AppendLine("        for (int i = 0; i < Count; i++)");
    sb.AppendLine("            yield return this[i];");
    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine("    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();");
    sb.AppendLine("}");
}

static string GenerateExtensionMethods(string[] levels, int maxArity)
{
    var groups = levels
        .Select(level => new MethodGroup(level, $"{level}InterpolatedStringHandler", $"LogLevel.{level}", ["logger"], null))
        .Append(new MethodGroup("Write", "LogInterpolatedStringHandler", "level", ["logger", "level"], "LogLevel level"))
        .ToArray();

    Combo[] combos =
    [
        new(["EventId eventId", "Exception? exception"], "eventId", "exception"),
        new(["EventId eventId"], "eventId", "null"),
        new(["Exception? exception"], "default", "exception"),
        new([], "default", "null"),
    ];

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using System.Runtime.CompilerServices;");
    sb.AppendLine("using Microsoft.Extensions.Logging;");
    sb.AppendLine();
    sb.AppendLine("namespace RandomSkunk.StructuredLogging;");
    sb.AppendLine();
    sb.AppendLine("/// <summary>");
    sb.AppendLine("/// Structured-logging extension methods for <see cref=\"ILogger\"/>.");
    sb.AppendLine("/// </summary>");
    sb.AppendLine("public static class StructuredLoggerExtensions");
    sb.AppendLine("{");

    bool first = true;
    foreach (var group in groups)
    {
        foreach (var combo in combos)
        {
            for (int arity = 0; arity <= maxArity; arity++)
            {
                if (!first)
                    sb.AppendLine();
                first = false;
                AppendArityMethod(sb, group, combo, arity);
            }

            sb.AppendLine();
            AppendParamsMethod(sb, group, combo);

            sb.AppendLine();
            AppendCollectionMethod(sb, group, combo);
        }
    }

    sb.AppendLine("}");
    return sb.ToString();
}

static string HandlerAttribute(MethodGroup group) =>
    "[InterpolatedStringHandlerArgument(" + string.Join(", ", group.HandlerArgNames.Select(n => $"\"{n}\"")) + ")]";

static List<string> BaseParameters(MethodGroup group, Combo combo)
{
    var parameters = new List<string> { "this ILogger logger" };
    if (group.LevelParam is not null)
        parameters.Add(group.LevelParam);
    parameters.AddRange(combo.Params);
    parameters.Add($"{HandlerAttribute(group)} {group.HandlerType} message");
    return parameters;
}

static void AppendArityMethod(StringBuilder sb, MethodGroup group, Combo combo, int arity)
{
    string typeParamList = arity == 0 ? string.Empty : $"<{string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"))}>";
    string stateType = arity == 0 ? "LogPropertiesState" : $"LogPropertiesState<{string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"))}>";

    var parameters = BaseParameters(group, combo);
    for (int i = 1; i <= arity; i++)
        parameters.Add($"(string Name, T{i} Value) logProperty{i}");

    sb.AppendLine($"    public static void {group.MethodName}{typeParamList}({string.Join(", ", parameters)})");
    sb.AppendLine("    {");
    sb.AppendLine($"        if (!logger.IsEnabled({group.LevelExpr}))");
    sb.AppendLine("            return;");
    sb.AppendLine();

    if (arity == 0)
    {
        sb.AppendLine($"        var state = new {stateType}(message.GetFormattedText(), Array.Empty<KeyValuePair<string, object?>>());");
    }
    else
    {
        var propArgs = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"logProperty{i}"));
        sb.AppendLine($"        var state = new {stateType}(message.GetFormattedText(), {propArgs});");
    }

    sb.AppendLine($"        logger.Log({group.LevelExpr}, {combo.EventIdArg}, state, {combo.ExceptionArg}, {stateType}.Formatter);");
    sb.AppendLine("    }");
}

static void AppendParamsMethod(StringBuilder sb, MethodGroup group, Combo combo)
{
    var parameters = BaseParameters(group, combo);
    parameters.Add("params (string Name, object? Value)[] logProperties");

    sb.AppendLine($"    public static void {group.MethodName}({string.Join(", ", parameters)})");
    sb.AppendLine("    {");
    sb.AppendLine($"        if (!logger.IsEnabled({group.LevelExpr}))");
    sb.AppendLine("            return;");
    sb.AppendLine();
    sb.AppendLine("        var state = new LogPropertiesState(message.GetFormattedText(), new TuplePropertyList(logProperties));");
    sb.AppendLine($"        logger.Log({group.LevelExpr}, {combo.EventIdArg}, state, {combo.ExceptionArg}, LogPropertiesState.Formatter);");
    sb.AppendLine("    }");
}

static void AppendCollectionMethod(StringBuilder sb, MethodGroup group, Combo combo)
{
    var parameters = BaseParameters(group, combo);
    parameters.Add("IReadOnlyCollection<KeyValuePair<string, object?>> logProperties");

    sb.AppendLine($"    public static void {group.MethodName}({string.Join(", ", parameters)})");
    sb.AppendLine("    {");
    sb.AppendLine($"        if (!logger.IsEnabled({group.LevelExpr}))");
    sb.AppendLine("            return;");
    sb.AppendLine();
    sb.AppendLine("        var properties = logProperties as IReadOnlyList<KeyValuePair<string, object?>> ?? logProperties.ToArray();");
    sb.AppendLine("        var state = new LogPropertiesState(message.GetFormattedText(), properties);");
    sb.AppendLine($"        logger.Log({group.LevelExpr}, {combo.EventIdArg}, state, {combo.ExceptionArg}, LogPropertiesState.Formatter);");
    sb.AppendLine("    }");
}

sealed record MethodGroup(string MethodName, string HandlerType, string LevelExpr, string[] HandlerArgNames, string? LevelParam);

sealed record Combo(string[] Params, string EventIdArg, string ExceptionArg);
